Meteor Engine: TAssetRef< T > Class Template Reference
TAssetRef< T > Class Template Reference
#include <asset_ref_handle.h>
Public Member Functions
TAssetRef ()=default
TAssetRef (const SString &assetId)
TAssetRef (const SString &assetId, const SString &path)
TAssetRef (const TAssetHandle< T > &handle)
TAssetRef (T *asset)
~TAssetRef ()=default
TAssetRef & operator= (const TAssetHandle< T > &handle)
TAssetRef & operator= (T *asset)
TAssetHandle< T > getHandle () const
T * resolve () const
T * operator-> () const
T & operator* () const
operator bool () const
bool isValid () const
bool isEmpty () const
const SString & getAssetId () const
void setAssetId (const SString &id)
const SString & getPath () const
void setPath (const SString &path)
bool operator== (const TAssetRef &other) const
bool operator!= (const TAssetRef &other) const
Constructor & Destructor Documentation
TAssetRef() [1/5]
template<typename T> TAssetRef< T >::TAssetRef () default
Referenced by operator!=(), operator=(), operator=(), and operator==().
TAssetRef() [2/5]
template<typename T> TAssetRef< T >::TAssetRef (const SString & assetId) inline explicit
TAssetRef() [3/5]
template<typename T> TAssetRef< T >::TAssetRef (const SString & assetId, const SString & path) inline
TAssetRef() [4/5]
template<typename T> TAssetRef< T >::TAssetRef (const TAssetHandle< T > & handle) inline
References TAssetHandle< T >::get(), getAssetId(), and T.
TAssetRef() [5/5]
template<typename T> TAssetRef< T >::TAssetRef (T * asset) inline
~TAssetRef()
template<typename T> TAssetRef< T >::~TAssetRef () default
Member Function Documentation
getAssetId()
template<typename T> const SString & TAssetRef< T >::getAssetId () const inline
Referenced by TAssetRef().
getHandle()
template<typename T> TAssetHandle< T > TAssetRef< T >::getHandle () const inline
References MEngineSubsystemRegistry::getSubsystem(), and T.
getPath()
template<typename T> const SString & TAssetRef< T >::getPath () const inline
isEmpty()
template<typename T> bool TAssetRef< T >::isEmpty () const inline
isValid()
template<typename T> bool TAssetRef< T >::isValid () const inline
References resolve().
operator bool()
template<typename T> TAssetRef< T >::operator bool () const inline explicit
References resolve().
operator!=()
template<typename T> bool TAssetRef< T >::operator!= (const TAssetRef< T > & other) const inline
References TAssetRef().
operator*()
template<typename T> T & TAssetRef< T >::operator* () const inline
References resolve().
operator->()
template<typename T> T * TAssetRef< T >::operator-> () const inline
References resolve().
operator=() [1/2]
template<typename T> TAssetRef & TAssetRef< T >::operator= (const TAssetHandle< T > & handle) inline
References TAssetHandle< T >::get(), TAssetHandle< T >::getAssetId(), T, and TAssetRef().
operator=() [2/2]
template<typename T> TAssetRef & TAssetRef< T >::operator= (T * asset) inline
References TAssetRef().
operator==()
template<typename T> bool TAssetRef< T >::operator== (const TAssetRef< T > & other) const inline
References SString::empty(), and TAssetRef().
resolve()
template<typename T> T * TAssetRef< T >::resolve () const inline
References MEngineSubsystemRegistry::getSubsystem(), and T.
Referenced by isValid(), operator bool(), operator*(), operator->(), and MStaticMeshEntity::setStaticMeshAsset().
setAssetId()
template<typename T> void TAssetRef< T >::setAssetId (const SString & id) inline
setPath()
template<typename T> void TAssetRef< T >::setPath (const SString & path) inline
The documentation for this class was generated from the following file:
src/core/engine/assetmanagement/asset/asset_ref_handle.h