Meteor Engine: SFrameBuffer Class Reference
SFrameBuffer Class Reference
#include <frame_buffer.h>
Public Member Functions
~SFrameBuffer () override
void bindAsActive () override
void unbind () override
bool makeBuffer (const SString &bufferName) override
bool resize (int width, int height) override
unsigned int getFBOHandle () const
unsigned int getColorTextureHandle () const
SVector2 getResolution () const
void setColorFormat (unsigned int glFormat)
Public Member Functions inherited from SBuffer
virtual bool isResizeable () const
SBuffer ()=default
virtual ~SBuffer ()=default
Constructor & Destructor Documentation
~SFrameBuffer()
SFrameBuffer::~SFrameBuffer () override
Member Function Documentation
bindAsActive()
void SFrameBuffer::bindAsActive () override virtual
Implements SBuffer.
Referenced by MClearStage::render(), MProceduralSkyboxStage::render(), and MSkyboxStage::render().
getColorTextureHandle()
unsigned int SFrameBuffer::getColorTextureHandle () const inline
getFBOHandle()
unsigned int SFrameBuffer::getFBOHandle () const inline
getResolution()
SVector2 SFrameBuffer::getResolution () const inline
makeBuffer()
bool SFrameBuffer::makeBuffer (const SString & bufferName) override virtual
Implements SBuffer.
resize()
bool SFrameBuffer::resize (int width, int height) override virtual
Reimplemented from SBuffer.
References MERROR.
setColorFormat()
void SFrameBuffer::setColorFormat (unsigned int glFormat) inline
Referenced by MLightingStage::init().
unbind()
void SFrameBuffer::unbind () override virtual
Implements SBuffer.
Referenced by MLightingStage::render().
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/buffers/frame/frame_buffer.h
src/core/graphics/core/render-pipeline/buffers/frame/frame_buffer.cpp