Meteor Engine: MAssetManager Class Reference
MAssetManager Class Reference
#include <assetmanager.h>
Public Member Functions
virtual void refresh ()
virtual void init () override
virtual void cleanup () override
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IAssetManagerSubsystem
IAssetManagerSubsystem ()
~IAssetManagerSubsystem () override=default
template<typename T>
TAssetHandle< T > getAsset (SString path)
template<typename T>
TAssetHandle< T > getAssetById (const SString &assetId)
template<typename T>
TAssetHandle< T > getAssetFromReference (const SString &refString)
Public Member Functions inherited from IEngineSubSystem
virtual ~IEngineSubSystem ()=default
virtual bool canTick ()
virtual void tick (float deltaTime)
Protected Member Functions
virtual void loadAssetRecursive (SString path)
virtual bool loadAsset (SString path)
virtual void addToDeferredLoadableAssetList (MAsset *asset)
void createMetaFile (const SString &filePath)
bool loadMetaData (const SString &path, pugi::xml_document &metaData)
bool hasMetaData (const SString &path)
Protected Member Functions inherited from IAssetManagerSubsystem
template<typename T>
T * internal_unsafe_getAsset (SString path)
template<typename T>
T * internal_unsafe_getAssetById (const SString &assetId)
Protected Attributes
std::vector< SString > ASSET_SEARCH_PATHS = {"assets/", "meteor_assets/engine_assets/"}
std::vector< MAsset * > defferedLoadableAssetList
Protected Attributes inherited from MObject
SString guid
SString name
Protected Attributes inherited from IAssetManagerSubsystem
const SString META_FILE_EXTENSION = "meta"
const SString ASSET_FILE_TAG = "asset_id"
const SString ASSET_ID_ATTRIB = "id"
std::map< SString, MAsset * > assetMap
std::map< SString, MAsset * > assetMapByAssetId
Static Protected Attributes
static MAssetManager * managerInstance
Static Protected Attributes inherited from IAssetManagerSubsystem
static constexpr const char * REF_GUID_PREFIX = "guid::"
static constexpr const char * REF_PATH_PREFIX = "rawp::"
static constexpr size_t REF_PREFIX_LEN = 6
static IAssetManagerSubsystem * instanceRef = nullptr
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Static Protected Member Functions inherited from IAssetManagerSubsystem
static MAsset * resolveByGuid (const SString &assetId)
Member Function Documentation
addToDeferredLoadableAssetList()
void MAssetManager::addToDeferredLoadableAssetList (MAsset * asset) protected virtual
References defferedLoadableAssetList.
Referenced by loadAsset().
cleanup()
void MAssetManager::cleanup () override virtual
Implements IEngineSubSystem.
References IAssetManagerSubsystem::assetMap, IAssetManagerSubsystem::assetMapByAssetId, and defferedLoadableAssetList.
Referenced by refresh().
createMetaFile()
void MAssetManager::createMetaFile (const SString & filePath) protected
References IAssetManagerSubsystem::ASSET_FILE_TAG, IAssetManagerSubsystem::ASSET_ID_ATTRIB, IAssetManagerSubsystem::META_FILE_EXTENSION, SGuid::newGUID(), and FileIO::writeFile().
Referenced by loadAsset().
hasMetaData()
bool MAssetManager::hasMetaData (const SString & path) protected
References FileIO::hasFile(), and IAssetManagerSubsystem::META_FILE_EXTENSION.
Referenced by loadAsset(), and loadMetaData().
init()
virtual void MAssetManager::init () inline override virtual
Implements IEngineSubSystem.
loadAsset()
bool MAssetManager::loadAsset (SString path) protected virtual
References addToDeferredLoadableAssetList(), IAssetManagerSubsystem::ASSET_FILE_TAG, IAssetManagerSubsystem::ASSET_ID_ATTRIB, IAssetManagerSubsystem::assetMap, IAssetManagerSubsystem::assetMapByAssetId, createMetaFile(), FileIO::getFileExtension(), MAssetImporter::getImporters(), hasMetaData(), loadMetaData(), MWARN, STR, and SString::str().
Referenced by loadAssetRecursive().
loadAssetRecursive()
void MAssetManager::loadAssetRecursive (SString path) protected virtual
References FileIO::getFileExtension(), loadAsset(), IAssetManagerSubsystem::META_FILE_EXTENSION, SString::replace(), STR, and SString::str().
Referenced by refresh().
loadMetaData()
bool MAssetManager::loadMetaData (const SString & path, pugi::xml_document & metaData) protected
References SString::c_str(), hasMetaData(), IAssetManagerSubsystem::META_FILE_EXTENSION, and FileIO::readFile().
Referenced by loadAsset().
refresh()
void MAssetManager::refresh () virtual
Implements IAssetManagerSubsystem.
Reimplemented in MEditorAssetManager.
References ASSET_SEARCH_PATHS, cleanup(), defferedLoadableAssetList, loadAssetRecursive(), MLOG, and STR.
Referenced by MEditorAssetManager::refresh().
Member Data Documentation
ASSET_SEARCH_PATHS
std::vector<SString> MAssetManager::ASSET_SEARCH_PATHS = {"assets/", "meteor_assets/engine_assets/"} protected
Referenced by refresh().
defferedLoadableAssetList
std::vector<MAsset*> MAssetManager::defferedLoadableAssetList protected
Referenced by addToDeferredLoadableAssetList(), cleanup(), and refresh().
managerInstance
MAssetManager* MAssetManager::managerInstance static protected
The documentation for this class was generated from the following files:
src/core/engine/assetmanagement/assetmanager/assetmanager.h
src/core/engine/assetmanagement/assetmanager/assetmanager.cpp