Meteor Engine: MMaterialPropertyControl Class Reference
MMaterialPropertyControl Class Reference
#include <material_properties_controls.h>
Public Member Functions
void draw (MMaterialAsset *asset)
void clearTextureReferences ()
int getLastPropertyCount () const
void setLastPropertyCount (int n)
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Static Public Member Functions
static bool canAcceptTextureAsset (MAsset *asset)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
canAcceptTextureAsset()
bool MMaterialPropertyControl::canAcceptTextureAsset (MAsset * asset) static
clearTextureReferences()
void MMaterialPropertyControl::clearTextureReferences ()
References SString::clear().
draw()
void MMaterialPropertyControl::draw (MMaterialAsset * asset)
References MMaterialAsset::getMaterial(), and MMaterial::getProperties().
getLastPropertyCount()
int MMaterialPropertyControl::getLastPropertyCount () const inline
setLastPropertyCount()
void MMaterialPropertyControl::setLastPropertyCount (int n) inline
The documentation for this class was generated from the following files:
src/editor/editorwindows/inspectordrawer/controls/material_properties_controls.h
src/editor/editorwindows/inspectordrawer/controls/material_properties_controls.cpp