Meteor Engine: MCompositeStage Class Reference
MCompositeStage Class Reference
#include <composite_stage.h>
Public Member Functions
int getSortingOrder () override
void init (IRenderPipeline *const pipeline) override
void cleanup (IRenderPipeline *const pipeline) override
void preRender (IRenderPipeline *const pipeline) override
void render (IRenderPipeline *const pipeline) override
void postRender (IRenderPipeline *const pipeline) override
Public Member Functions inherited from MRenderStage
MRenderStage ()=default
~MRenderStage () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IRenderStage
virtual ~IRenderStage ()=default
Static Public Attributes
static EBufferDebugView debugView = EBufferDebugView::Final
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MCompositeStage::cleanup (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
getSortingOrder()
int MCompositeStage::getSortingOrder () inline override virtual
Implements MRenderStage.
References RS_Composite.
init()
void MCompositeStage::init (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References MEngineSubsystemRegistry::getSubsystem(), and MERROR.
postRender()
void MCompositeStage::postRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
preRender()
void MCompositeStage::preRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
render()
void MCompositeStage::render (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References SRenderBuffer::bindAsActive(), debugView, ECF_Depth, ECF_Lights, ECF_None, ECF_Opaque, Final, IRenderPipeline::getCompositeFlags(), IRenderPipeline::getRenderBuffer(), and IRenderPipeline::getRenderResolution().
Member Data Documentation
debugView
EBufferDebugView MCompositeStage::debugView = EBufferDebugView::Final static
Referenced by render().
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/composite/composite_stage.h
src/core/graphics/core/render-pipeline/stages/composite/composite_stage.cpp