Meteor Engine: SShaderPropertyValue Struct Reference
SShaderPropertyValue Struct Reference
#include <shader.h>
Public Member Functions
SShaderPropertyType getType () const
int getIntVal () const
float getFloatVal () const
glm::vec2 getVec2Val () const
glm::vec3 getVec3Val () const
glm::vec4 getVec4Val () const
glm::vec4 getColor () const
SMatrix4 getMat4Val () const
bool getBoolValue () const
SString getTexAssetReference () const
void setIntVal (int val)
void setFloatVal (float val)
void setVec2Val (glm::vec2 val)
void setVec3Val (glm::vec3 val)
void setColVal (glm::vec4 val)
void setVec4Val (glm::vec4 val)
void setMat4Val (glm::mat4 val)
void setBoolValue (bool val)
void setTextureReference (SString texturePath)
void print ()
Member Function Documentation
getBoolValue()
bool SShaderPropertyValue::getBoolValue () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), and MShader::setPropertyValue().
getColor()
glm::vec4 SShaderPropertyValue::getColor () const inline nodiscard
Referenced by MShaderUtility::getValueStr().
getFloatVal()
float SShaderPropertyValue::getFloatVal () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), print(), and MShader::setPropertyValue().
getIntVal()
int SShaderPropertyValue::getIntVal () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), print(), and MShader::setPropertyValue().
getMat4Val()
SMatrix4 SShaderPropertyValue::getMat4Val () const inline nodiscard
Referenced by print(), and MShader::setPropertyValue().
getTexAssetReference()
SString SShaderPropertyValue::getTexAssetReference () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), and MShader::setPropertyValue().
getType()
SShaderPropertyType SShaderPropertyValue::getType () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), and MShader::setPropertyValue().
getVec2Val()
glm::vec2 SShaderPropertyValue::getVec2Val () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), print(), and MShader::setPropertyValue().
getVec3Val()
glm::vec3 SShaderPropertyValue::getVec3Val () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), print(), and MShader::setPropertyValue().
getVec4Val()
glm::vec4 SShaderPropertyValue::getVec4Val () const inline nodiscard
Referenced by MShaderUtility::getValueStr(), print(), and MShader::setPropertyValue().
print()
void SShaderPropertyValue::print ()
References Float, getFloatVal(), getIntVal(), getMat4Val(), getVec2Val(), getVec3Val(), getVec4Val(), Int, Matrix4, MLOG, STR, UniformVec2, UniformVec3, and UniformVec4.
setBoolValue()
void SShaderPropertyValue::setBoolValue (bool val) inline
References Bool.
Referenced by MShaderUtility::parseValue().
setColVal()
void SShaderPropertyValue::setColVal (glm::vec4 val) inline
References Color.
Referenced by MShaderUtility::parseValue().
setFloatVal()
void SShaderPropertyValue::setFloatVal (float val) inline
References Float.
Referenced by MShaderUtility::parseValue().
setIntVal()
void SShaderPropertyValue::setIntVal (int val) inline
References Int.
Referenced by MShaderUtility::parseValue().
setMat4Val()
void SShaderPropertyValue::setMat4Val (glm::mat4 val) inline
References Matrix4.
Referenced by MSkyboxDrawCall::draw(), MGizmos::drawLine(), MGizmos::drawTextureRect(), MDepthRenderStage::render(), and MLightingStage::render().
setTextureReference()
void SShaderPropertyValue::setTextureReference (SString texturePath) inline
References Texture.
Referenced by MShaderUtility::parseValue().
setVec2Val()
void SShaderPropertyValue::setVec2Val (glm::vec2 val) inline
References UniformVec2.
Referenced by MShaderUtility::parseValue().
setVec3Val()
void SShaderPropertyValue::setVec3Val (glm::vec3 val) inline
References UniformVec3.
Referenced by MShaderUtility::parseValue().
setVec4Val()
void SShaderPropertyValue::setVec4Val (glm::vec4 val) inline
References UniformVec4.
Referenced by MGizmos::drawLine(), and MShaderUtility::parseValue().
The documentation for this struct was generated from the following files:
src/core/graphics/core/shader/shader.h
src/core/graphics/core/shader/shader.cpp