Meteor Engine: MEditorSceneViewWindow Class Reference
MEditorSceneViewWindow Class Reference
#include <editorsceneviewwindow.h>
Public Member Functions
MEditorSceneViewWindow ()
MEditorSceneViewWindow (int x, int y)
void onGui (float deltaTime) override
void handleInput (float dt) override
Public Member Functions inherited from MImGuiSubWindow
MImGuiSubWindow (int x, int y)
SString getTitle () const
MImGuiSubWindow (const SString &title, int x, int y)
~MImGuiSubWindow ()
void setWindowConstraints (float minx, float miny, float maxx, float maxy)
void draw (float deltaTime)
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MImGuiSubWindow
SString title
ImVec2 minSize = ImVec2(0, 0)
ImVec2 maxSize = ImVec2(FLT_MAX, FLT_MAX)
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MEditorSceneViewWindow() [1/2]
MEditorSceneViewWindow::MEditorSceneViewWindow ()
References MEditorSceneViewWindow().
Referenced by MEditorSceneViewWindow().
MEditorSceneViewWindow() [2/2]
MEditorSceneViewWindow::MEditorSceneViewWindow (int x, int y) explicit
References MEditorApplication::getSceneCamera(), SEditorAssetPaths::LOWRES_TEX_BTTN_GIZMO_DISABLED, SEditorAssetPaths::LOWRES_TEX_BTTN_GIZMO_ENABLED, SEditorAssetPaths::LOWRES_TEX_BTTN_GIZMO_LOCALSPACE, SEditorAssetPaths::LOWRES_TEX_BTTN_GIZMO_WORLDSPACE, SEditorAssetPaths::LOWRES_TEX_BTTN_MOVE, SEditorAssetPaths::LOWRES_TEX_BTTN_ROTATE, SEditorAssetPaths::LOWRES_TEX_BTTN_SCALE, MImGuiSubWindow::MImGuiSubWindow(), and MImGuiSubWindow::title.
Member Function Documentation
handleInput()
void MEditorSceneViewWindow::handleInput (float dt) override virtual
Reimplemented from MImGuiSubWindow.
References MViewManagement::getCameras().
onGui()
void MEditorSceneViewWindow::onGui (float deltaTime) override virtual
Implements MImGuiSubWindow.
References MAssetReferenceControl::ASSET_REF_TARGET_KEY, SceneRaycast::castRay(), MSpatialEntity::createInstance(), MSceneManager::getActiveScene(), MViewManagement::getCameras(), MSceneManager::getSceneManagerInstance(), MEngineSubsystemRegistry::getSubsystem(), SRaycastHit::point, and MEditorApplication::SelectedObject.
The documentation for this class was generated from the following files:
src/editor/editorwindows/scene/editorsceneviewwindow.h
src/editor/editorwindows/scene/editorsceneviewwindow.cpp