Meteor Engine: MBufferRegistery Class Reference
MBufferRegistery Class Reference
#include <buffer_registry.h>
Public Member Functions
~MBufferRegistery () override
template<typename T>
T * createBuffer (const SString &name)
template<typename T = SBuffer>
T * getBuffer (const SString &name) const
void resizeAll (int width, int height)
void setRenderBuffer (SRenderBuffer *renderBuffer)
SRenderBuffer * getRenderBuffer () const
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
~MBufferRegistery()
MBufferRegistery::~MBufferRegistery () override
References MObject::name.
Member Function Documentation
createBuffer()
template<typename T> T * MBufferRegistery::createBuffer (const SString & name) inline
References MObject::name, and T.
Referenced by MDepthRenderStage::init(), MLightingStage::init(), MOpaqueStage::init(), and MShadowStage::init().
getBuffer()
template<typename T = SBuffer> T * MBufferRegistery::getBuffer (const SString & name) const inline
References MObject::name, and T.
Referenced by MProceduralSkyboxStage::init(), MSkyboxStage::init(), MProceduralSkyboxStage::preRender(), MSkyboxStage::preRender(), MClearStage::render(), MGizmoStage::render(), and MLightingStage::render().
getRenderBuffer()
SRenderBuffer * MBufferRegistery::getRenderBuffer () const inline
resizeAll()
void MBufferRegistery::resizeAll (int width, int height)
References MWARN, and MObject::name.
setRenderBuffer()
void MBufferRegistery::setRenderBuffer (SRenderBuffer * renderBuffer)
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/buffer_registry.h
src/core/graphics/core/render-pipeline/buffer_registry.cpp