Meteor Engine: MLightingStage Class Reference
MLightingStage Class Reference
#include <lighting_stage.h>
Public Member Functions
int getSortingOrder () override
void init (IRenderPipeline *const pipeline) override
void cleanup (IRenderPipeline *const pipeline) override
void preRender (IRenderPipeline *const pipeline) override
void render (IRenderPipeline *const pipeline) override
void postRender (IRenderPipeline *const pipeline) override
Public Member Functions inherited from MRenderStage
MRenderStage ()=default
~MRenderStage () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IRenderStage
virtual ~IRenderStage ()=default
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MLightingStage::cleanup (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
getSortingOrder()
int MLightingStage::getSortingOrder () inline override virtual
Implements MRenderStage.
References RS_Lighting.
init()
void MLightingStage::init (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References MBufferNames::BUFFER_LIGHTS, MBufferRegistery::createBuffer(), IRenderPipeline::getBufferRegistry(), MEngineSubsystemRegistry::getSubsystem(), MERROR, and SFrameBuffer::setColorFormat().
postRender()
void MLightingStage::postRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
preRender()
void MLightingStage::preRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
render()
void MLightingStage::render (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References IRenderPipeline::addCompositeFlag(), MShader::bind(), MBufferNames::BUFFER_OPAQUE, MBufferNames::BUFFER_SHADOW, ECF_Lights, ECF_Shadow, MBufferRegistery::getBuffer(), IRenderPipeline::getBufferRegistry(), MViewManagement::getCameras(), IRenderPipeline::getCompositeFlags(), SDepthBuffer::getFBOHandle(), MLightSystemManager::getInstance(), MCameraEntity::getProjectionMatrix(), IRenderPipeline::getRenderItems(), IRenderPipeline::getRenderResolution(), MEngineSubsystemRegistry::getSubsystem(), MCameraEntity::getViewMatrix(), AABB::max, SShadowBuffer::MAX_POINT_SHADOWS, SShadowBuffer::MAX_SPOT_SHADOWS, AABB::min, MWARN, SShaderPropertyValue::setMat4Val(), MShader::setPropertyValue(), Texture, SFrameBuffer::unbind(), and MMaterial::Unlit.
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/lighting/lighting_stage.h
src/core/graphics/core/render-pipeline/stages/lighting/lighting_stage.cpp