Meteor Engine: MEditorThemes Class Reference
MEditorThemes Class Reference
#include <editor_themes.h>
Static Public Member Functions
static void applyTheme ()
Member Function Documentation
applyTheme()
void MEditorThemes::applyTheme () static
References SString::format(), MEngineStatics::getEngineSettings(), MVERBOSE, and MWARN.
Referenced by MImGuiWindow::initialiseWindow().
The documentation for this class was generated from the following files:
src/editor/themes/editor_themes.h
src/editor/themes/editor_themes.cpp