Meteor Engine: SRaycastHit Struct Reference
SRaycastHit Struct Reference
#include <scene_raycast.h>
Public Attributes
SVector3 point = SVector3(0.f)
SVector3 normal = SVector3(0.f, 1.f, 0.f)
float distance = std::numeric_limits<float>::max()
bool hit = false
Member Data Documentation
distance
float SRaycastHit::distance = std::numeric_limits<float>::max()
Referenced by SceneRaycast::castRay().
hit
bool SRaycastHit::hit = false
Referenced by SceneRaycast::castRay().
normal
SVector3 SRaycastHit::normal = SVector3(0.f, 1.f, 0.f)
Referenced by SceneRaycast::castRay().
point
SVector3 SRaycastHit::point = SVector3(0.f)
Referenced by SceneRaycast::castRay(), and MEditorSceneViewWindow::onGui().
The documentation for this struct was generated from the following file:
src/editor/editorwindows/scene/scene_raycast.h