Meteor Engine: MLogger Class Reference
MLogger Class Reference
#include <logger.h>
Static Public Member Functions
static void log (SString msg, SLogLocation loc={})
static void verbose (SString msg, SLogLocation loc={})
static void warn (SString warning, SLogLocation loc={})
static void error (SString error, SLogLocation loc={})
static int subscribe (const LogEventHandler &handler)
static void unsubscribe (const int &id)
static SString getLastMessage ()
Member Function Documentation
error()
void MLogger::error (SString error, SLogLocation loc = {}) static
References error(), SLogMessage::location, SLogMessage::stackTrace, STR, SLogMessage::tag, SLogMessage::text, and SLogMessage::timestamp.
Referenced by error().
getLastMessage()
SString MLogger::getLastMessage () static
Referenced by MEditorApplication::showSplashScreen().
log()
void MLogger::log (SString msg, SLogLocation loc = {}) static
References SLogMessage::location, STR, SString::str(), SLogMessage::tag, SLogMessage::text, and SLogMessage::timestamp.
Referenced by verbose().
subscribe()
int MLogger::subscribe (const LogEventHandler & handler) static
Referenced by MEditorConsoleWindow::MEditorConsoleWindow().
unsubscribe()
void MLogger::unsubscribe (const int & id) static
Referenced by MEditorConsoleWindow::~MEditorConsoleWindow().
verbose()
void MLogger::verbose (SString msg, SLogLocation loc = {}) static
References log().
warn()
void MLogger::warn (SString warning, SLogLocation loc = {}) static
References SLogMessage::location, STR, SString::str(), SLogMessage::tag, SLogMessage::text, and SLogMessage::timestamp.
The documentation for this class was generated from the following files:
src/core/utils/logger.h
src/core/utils/logger.cpp