Meteor Engine: MOpaqueStage Class Reference
MOpaqueStage Class Reference
#include <opaque_stage.h>
Public Member Functions
int getSortingOrder () override
void init (IRenderPipeline *const pipeline) override
void cleanup (IRenderPipeline *const pipeline) override
void preRender (IRenderPipeline *const pipeline) override
void render (IRenderPipeline *const pipeline) override
void postRender (IRenderPipeline *const pipeline) override
Public Member Functions inherited from MRenderStage
MRenderStage ()=default
~MRenderStage () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IRenderStage
virtual ~IRenderStage ()=default
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MOpaqueStage::cleanup (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
getSortingOrder()
int MOpaqueStage::getSortingOrder () inline override virtual
Implements MRenderStage.
References RS_Opaque.
init()
void MOpaqueStage::init (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References MBufferNames::BUFFER_OPAQUE, MBufferRegistery::createBuffer(), IRenderPipeline::getBufferRegistry(), and MERROR.
postRender()
void MOpaqueStage::postRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
preRender()
void MOpaqueStage::preRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References MLightSystemManager::getInstance(), and MLightSystemManager::prepareLights().
render()
void MOpaqueStage::render (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References IRenderPipeline::addCompositeFlag(), ECF_Opaque, MViewManagement::getCameras(), MLightSystemManager::getInstance(), MCameraEntity::getProjectionMatrix(), IRenderPipeline::getRenderItems(), IRenderPipeline::getRenderResolution(), MCameraEntity::getViewMatrix(), AABB::max, AABB::min, and MLightSystemManager::prepareDynamicLights().
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/opaque/opaque_stage.h
src/core/graphics/core/render-pipeline/stages/opaque/opaque_stage.cpp