Meteor Engine: MEditorAssetManager Class Reference
MEditorAssetManager Class Reference
#include <editorassetmanager.h>
Public Member Functions
void refresh () override
void openAsset (MAsset *asset)
virtual int saveDirtyAssets ()
int tickHotReload ()
int getTotalHotReloadCount () const
SAssetDirectoryNode * getAssetRootNode () const
void pingAsset (const SString &assetId)
SString consumePendingPing ()
sf::Texture * getThumbnail (MAsset *asset)
void requestThumbnail (MAsset *asset)
Public Member Functions inherited from MAssetManager
virtual void init () override
virtual void cleanup () override
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IAssetManagerSubsystem
IAssetManagerSubsystem ()
~IAssetManagerSubsystem () override=default
template<typename T>
TAssetHandle< T > getAsset (SString path)
template<typename T>
TAssetHandle< T > getAssetById (const SString &assetId)
template<typename T>
TAssetHandle< T > getAssetFromReference (const SString &refString)
Public Member Functions inherited from IEngineSubSystem
virtual ~IEngineSubSystem ()=default
virtual bool canTick ()
virtual void tick (float deltaTime)
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Member Functions inherited from MAssetManager
virtual void loadAssetRecursive (SString path)
virtual bool loadAsset (SString path)
virtual void addToDeferredLoadableAssetList (MAsset *asset)
void createMetaFile (const SString &filePath)
bool loadMetaData (const SString &path, pugi::xml_document &metaData)
bool hasMetaData (const SString &path)
Protected Member Functions inherited from IAssetManagerSubsystem
template<typename T>
T * internal_unsafe_getAsset (SString path)
template<typename T>
T * internal_unsafe_getAssetById (const SString &assetId)
Static Protected Member Functions inherited from IAssetManagerSubsystem
static MAsset * resolveByGuid (const SString &assetId)
Protected Attributes inherited from MAssetManager
std::vector< SString > ASSET_SEARCH_PATHS = {"assets/", "meteor_assets/engine_assets/"}
std::vector< MAsset * > defferedLoadableAssetList
Protected Attributes inherited from MObject
SString guid
SString name
Protected Attributes inherited from IAssetManagerSubsystem
const SString META_FILE_EXTENSION = "meta"
const SString ASSET_FILE_TAG = "asset_id"
const SString ASSET_ID_ATTRIB = "id"
std::map< SString, MAsset * > assetMap
std::map< SString, MAsset * > assetMapByAssetId
Static Protected Attributes inherited from MAssetManager
static MAssetManager * managerInstance
Static Protected Attributes inherited from IAssetManagerSubsystem
static constexpr const char * REF_GUID_PREFIX = "guid::"
static constexpr const char * REF_PATH_PREFIX = "rawp::"
static constexpr size_t REF_PREFIX_LEN = 6
static IAssetManagerSubsystem * instanceRef = nullptr
Member Function Documentation
consumePendingPing()
SString MEditorAssetManager::consumePendingPing () inline
References SString::clear().
getAssetRootNode()
SAssetDirectoryNode * MEditorAssetManager::getAssetRootNode () const inline nodiscard
Referenced by MEditorAssetWindow::MEditorAssetWindow().
getThumbnail()
sf::Texture * MEditorAssetManager::getThumbnail (MAsset * asset)
References MAsset::getAssetId(), and MObject::isDirty().
getTotalHotReloadCount()
int MEditorAssetManager::getTotalHotReloadCount () const inline
openAsset()
void MEditorAssetManager::openAsset (MAsset * asset)
References SString::format(), MAsset::getFullPath(), MObject::getName(), MLOG, MAsset::openAsset(), and STR.
pingAsset()
void MEditorAssetManager::pingAsset (const SString & assetId) inline
Referenced by MAssetReferenceControl::drawCompactControl().
refresh()
void MEditorAssetManager::refresh () override virtual
Reimplemented from MAssetManager.
References MAssetManager::refresh().
requestThumbnail()
void MEditorAssetManager::requestThumbnail (MAsset * asset)
saveDirtyAssets()
int MEditorAssetManager::saveDirtyAssets () virtual
References IAssetManagerSubsystem::assetMap, MObject::clearDirty(), SString::format(), MObject::isDirty(), MLOG, and MAsset::save().
tickHotReload()
int MEditorAssetManager::tickHotReload ()
The documentation for this class was generated from the following files:
src/editor/editorassetmanager/editorassetmanager.h
src/editor/editorassetmanager/editorassetmanager.cpp