Meteor Engine: MMiniAudioSource Class Reference
MMiniAudioSource Class Reference
#include <audio_source.h>
Public Member Functions
void init () override
void tick (const float &deltaTime) override
void cleanup () override
void internal_setEngineHandle (ma_engine *internalEngineHandle)
void setClip (IAudioClip *clip) override
void play () override
void stop () override
void setLooping (const bool &looping) override
void setVolume (const float &volume) override
void setPitch (const float &pitch) override
void setSpatializationEnabled (const bool &enabled) override
void setRollOff (const float &rollOff) override
void setMinDist (const float &minDist) override
void setMaxDist (const float &maxDist) override
void setDopplerStrength (const float &strength) override
void setPosition (const SVector3 &position) override
void setDirection (const SVector3 &direction) override
void setVelocity (const SVector3 &velocity) override
void internal_testClip (SString clipPath)
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IAudioSource
virtual ~IAudioSource ()=default
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MMiniAudioSource::cleanup () override virtual
Implements IAudioSource.
References MLOG.
init()
void MMiniAudioSource::init () override virtual
Implements IAudioSource.
References MERROR, and MLOG.
internal_setEngineHandle()
void MMiniAudioSource::internal_setEngineHandle (ma_engine * internalEngineHandle) inline
internal_testClip()
void MMiniAudioSource::internal_testClip (SString clipPath)
References SString::c_str(), MERROR, and MLOG.
play()
void MMiniAudioSource::play () override virtual
Implements IAudioSource.
setClip()
void MMiniAudioSource::setClip (IAudioClip * clip) override virtual
Implements IAudioSource.
References SString::c_str(), IAudioClip::getFilePath(), MERROR, and MLOG.
setDirection()
void MMiniAudioSource::setDirection (const SVector3 & direction) override virtual
Implements IAudioSource.
setDopplerStrength()
void MMiniAudioSource::setDopplerStrength (const float & strength) override virtual
Implements IAudioSource.
setLooping()
void MMiniAudioSource::setLooping (const bool & looping) override virtual
Implements IAudioSource.
setMaxDist()
void MMiniAudioSource::setMaxDist (const float & maxDist) override virtual
Implements IAudioSource.
setMinDist()
void MMiniAudioSource::setMinDist (const float & minDist) override virtual
Implements IAudioSource.
setPitch()
void MMiniAudioSource::setPitch (const float & pitch) override virtual
Implements IAudioSource.
setPosition()
void MMiniAudioSource::setPosition (const SVector3 & position) override virtual
Implements IAudioSource.
setRollOff()
void MMiniAudioSource::setRollOff (const float & rollOff) override virtual
Implements IAudioSource.
setSpatializationEnabled()
void MMiniAudioSource::setSpatializationEnabled (const bool & enabled) override virtual
Implements IAudioSource.
setVelocity()
void MMiniAudioSource::setVelocity (const SVector3 & velocity) override virtual
Implements IAudioSource.
setVolume()
void MMiniAudioSource::setVolume (const float & volume) override virtual
Implements IAudioSource.
stop()
void MMiniAudioSource::stop () override virtual
Implements IAudioSource.
tick()
void MMiniAudioSource::tick (const float & deltaTime) override virtual
Implements IAudioSource.
The documentation for this class was generated from the following files:
src/core/engine/audio/impl_miniaudio/audio_source.h
src/core/engine/audio/impl_miniaudio/audio_source.cpp