Meteor Engine: MShortcutBinding Struct Reference
MShortcutBinding Struct Reference
#include <shortcut_listener.h>
Public Member Functions
bool isValid () const
std::string getDisplayText () const
Public Attributes
EKeyCode key = EKeyCode::Unknown
bool ctrl = false
bool shift = false
bool alt = false
Member Function Documentation
getDisplayText()
std::string MShortcutBinding::getDisplayText () const nodiscard
References alt, ctrl, SInput::getKeyName(), isValid(), key, and shift.
Referenced by MMenubarTreeNode::renderAsContextMenu().
isValid()
bool MShortcutBinding::isValid () const inline nodiscard
References key, and Unknown.
Referenced by getDisplayText(), and MShortcutListener::registerShortcut().
Member Data Documentation
alt
bool MShortcutBinding::alt = false
Referenced by getDisplayText().
ctrl
bool MShortcutBinding::ctrl = false
Referenced by getDisplayText().
key
EKeyCode MShortcutBinding::key = EKeyCode::Unknown
Referenced by getDisplayText(), and isValid().
shift
bool MShortcutBinding::shift = false
Referenced by getDisplayText().
The documentation for this struct was generated from the following files:
src/editor/app/shortcut_listener.h
src/editor/app/shortcut_listener.cpp