Meteor Engine: MEngineSubsystemRegistry Class Reference
MEngineSubsystemRegistry Class Reference
#include <subsystem_registry.h>
Static Public Member Functions
static void init ()
static void cleanup ()
template<typename TInterface, typename TConcrete = TInterface, typename... Args>
static TInterface * registerSubsystem (bool autoInit=true, Args &&... args)
template<typename T>
static T * getSubsystem ()
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MEngineSubsystemRegistry::cleanup () static
References MLOG.
Referenced by main().
getSubsystem()
template<typename T> T * MEngineSubsystemRegistry::getSubsystem () inline static
References T.
Referenced by MMaterialAsset::buildMaterialAsset(), MMaterialAsset::createNewMaterial(), MSkyboxEntityDeserialiser::deserialize(), MStaticMeshEntityDeserialiser::deserialize(), MAssetReferenceControl::drawCompactControl(), MGizmos::drawLine(), MGizmos::drawTextureRect(), MAssetReferenceControl::getAssetReference(), MAudioClipAsset::getAudioClip(), TAssetRef< T >::getHandle(), MCompositeStage::init(), MDepthRenderStage::init(), MLightingStage::init(), MShadowStage::init(), MWindow::initialiseWindow(), MSceneManager::loadScene(), MEditorAssetWindow::MEditorAssetWindow(), MProceduralSkyboxEntity::MProceduralSkyboxEntity(), MSkyboxEntity::MSkyboxEntity(), MAudioListener::onCreate(), MAudioSource::onCreate(), MSkyboxEntity::onDeserialise(), MAmbientLightEntity::onDrawGizmo(), MAudioListener::onDrawGizmo(), MAudioSource::onDrawGizmo(), MCameraEntity::onDrawGizmo(), MDirectionalLight::onDrawGizmo(), MPointLight::onDrawGizmo(), MProceduralSkyboxEntity::onDrawGizmo(), MSkyboxEntity::onDrawGizmo(), MSpotLight::onDrawGizmo(), MEditorSceneViewWindow::onGui(), MAssetInspector::releaseAudioPreview(), MAudioClipAsset::releaseClip(), MLightingStage::render(), TAssetRef< T >::resolve(), MStaticMeshEntity::submitRenderItem(), and MWindow::update().
init()
void MEngineSubsystemRegistry::init () static
References MLOG.
Referenced by main().
registerSubsystem()
template<typename TInterface, typename TConcrete = TInterface, typename... Args> TInterface * MEngineSubsystemRegistry::registerSubsystem (bool autoInit = true, Args &&... args) inline static
The documentation for this class was generated from the following files:
src/core/engine/subsystem/subsystem_registry.h
src/core/engine/subsystem/subsystem_registry.cpp