Meteor Engine: MImGuiWindow Class Reference
MImGuiWindow Class Reference
#include <imguiwindow.h>
Public Member Functions
bool initialiseWindow (const SString &inTitle, SVector2 inSize, int inFps) override
void clear () override
void update (float deltaTime) override
void close () override
void drawImGuiSubWindows (float deltaTime)
void showDockSpace ()
void drawMenuBar ()
void drawControls ()
void setGraphicsCall (std::function< void(void)> func)
void loadFontFile (const SString &pathToFile, float pointSize)
Public Member Functions inherited from MWindow
MWindow ()=default
virtual ~MWindow ()
virtual bool isOpen () const
void setWindowResizeCallback (std::function< void(SVector2)> inCallback)
void setVisible (bool visible)
SRenderBuffer * getRenderBuffer ()
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Static Public Attributes inherited from MWindow
static const int DEFAULT_FPS = 60
static const SVector2 DEFAULT_WINDOW_SIZE {800, 600}
Protected Member Functions inherited from MWindow
void handleWindowEvents (const std::optional< sf::Event > &event)
Protected Attributes inherited from MWindow
int targetFPS = 0
sf::Clock clock
sf::ContextSettings settings
SString title = "Window Instance"
sf::RenderWindow coreWindow
sf::Clock deltaClock
SVector2 windowSize
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
clear()
void MImGuiWindow::clear () override virtual
Reimplemented from MWindow.
References MWindow::clear().
close()
void MImGuiWindow::close () override virtual
Reimplemented from MWindow.
References MWindow::close().
drawControls()
void MImGuiWindow::drawControls ()
References MEditorControlsButtons::runtimeControls().
Referenced by drawMenuBar().
drawImGuiSubWindows()
void MImGuiWindow::drawImGuiSubWindows (float deltaTime)
References MImGuiSubWindowManager::getSubWindows().
drawMenuBar()
void MImGuiWindow::drawMenuBar ()
References drawControls(), and MMenubarTreeNode::getRoot().
initialiseWindow()
bool MImGuiWindow::initialiseWindow (const SString & inTitle, SVector2 inSize, int inFps) override virtual
Reimplemented from MWindow.
References MEditorThemes::applyTheme(), MWindow::coreWindow, DPIHelper::GetDPIScaleFactor(), MWindow::initialiseWindow(), loadFontFile(), MERROR, and STR.
loadFontFile()
void MImGuiWindow::loadFontFile (const SString & pathToFile, float pointSize)
References SString::c_str(), MERROR, MWARN, and STR.
Referenced by initialiseWindow().
setGraphicsCall()
void MImGuiWindow::setGraphicsCall (std::function< void(void)> func) inline
showDockSpace()
void MImGuiWindow::showDockSpace ()
References MAIN_DOCKSPACE_ID.
update()
void MImGuiWindow::update (float deltaTime) override virtual
Reimplemented from MWindow.
References MWindow::clock, MWindow::coreWindow, MWindow::handleWindowEvents(), and MWindow::targetFPS.
The documentation for this class was generated from the following files:
src/editor/window/imgui/imguiwindow.h
src/editor/window/imgui/imguiwindow.cpp