Meteor Engine: MEngineStatics Class Reference
MEngineStatics Class Reference
#include <engine_statics.h>
Static Public Member Functions
static void saveAll ()
static MEngineSettings * getEngineSettings ()
template<typename T>
static void loadEngineSettings (const SString &path)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
getEngineSettings()
MEngineSettings * MEngineStatics::getEngineSettings () inline static
Referenced by MEditorThemes::applyTheme(), MEditorApplication::initialise(), MPlayerApplication::initialise(), MEditorSceneManager::loadScene(), and MEditorSceneCameraEntity::onCreate().
loadEngineSettings()
template<typename T> void MEngineStatics::loadEngineSettings (const SString & path) inline static
References SString::format(), FileIO::hasFile(), MWARN, and T.
Referenced by MEditorApplication::initialise(), and MPlayerApplication::initialise().
saveAll()
void MEngineStatics::saveAll () static
References MLOG.
Referenced by MEditorApplication::exit(), MEditorApplication::initialise(), and main().
The documentation for this class was generated from the following files:
src/core/engine/engine_statics.h
src/core/engine/engine_statics.cpp