Meteor Engine: MClearStage Class Reference
MClearStage Class Reference
#include <clear_stage.h>
Public Member Functions
int getSortingOrder () override
void init (IRenderPipeline *const pipeline) override
void cleanup (IRenderPipeline *const pipeline) override
void preRender (IRenderPipeline *const pipeline) override
void render (IRenderPipeline *const pipeline) override
void postRender (IRenderPipeline *const pipeline) override
Public Member Functions inherited from MRenderStage
MRenderStage ()=default
~MRenderStage () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IRenderStage
virtual ~IRenderStage ()=default
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MClearStage::cleanup (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
getSortingOrder()
int MClearStage::getSortingOrder () inline override virtual
Implements MRenderStage.
References RS_Clear.
init()
void MClearStage::init (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
postRender()
void MClearStage::postRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
preRender()
void MClearStage::preRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
render()
void MClearStage::render (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References SFrameBuffer::bindAsActive(), MBufferNames::BUFFER_OPAQUE, MBufferRegistery::getBuffer(), IRenderPipeline::getBufferRegistry(), and IRenderPipeline::getRenderResolution().
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/clear/clear_stage.h
src/core/graphics/core/render-pipeline/stages/clear/clear_stage.cpp