Meteor Engine: MProceduralSkyboxDrawCall Class Reference
MProceduralSkyboxDrawCall Class Reference
#include <procedural_skybox_drawcall.h>
Public Member Functions
MProceduralSkyboxDrawCall (MShader *shader)
~MProceduralSkyboxDrawCall ()
void setTargetResolution (const SVector2 &res)
void draw ()
void setSunDirection (const SVector3 &dir)
void setSunSize (float v)
void setSunSizeConvergence (float v)
void setAtmosphereThickness (float v)
void setSkyTint (const SVector3 &v)
void setGroundColor (const SVector3 &v)
void setExposure (float v)
SVector3 getSunDirection () const
float getSunSize () const
float getSunSizeConvergence () const
float getAtmosphereThickness () const
SVector3 getSkyTint () const
SVector3 getGroundColor () const
float getExposure () const
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MProceduralSkyboxDrawCall()
MProceduralSkyboxDrawCall::MProceduralSkyboxDrawCall (MShader * shader) explicit
~MProceduralSkyboxDrawCall()
MProceduralSkyboxDrawCall::~MProceduralSkyboxDrawCall ()
Member Function Documentation
draw()
void MProceduralSkyboxDrawCall::draw ()
References MViewManagement::getCameras(), MCameraEntity::getProjectionMatrix(), MCameraEntity::getViewMatrix(), and MERROR.
getAtmosphereThickness()
float MProceduralSkyboxDrawCall::getAtmosphereThickness () const inline nodiscard
getExposure()
float MProceduralSkyboxDrawCall::getExposure () const inline nodiscard
getGroundColor()
SVector3 MProceduralSkyboxDrawCall::getGroundColor () const inline nodiscard
getSkyTint()
SVector3 MProceduralSkyboxDrawCall::getSkyTint () const inline nodiscard
getSunDirection()
SVector3 MProceduralSkyboxDrawCall::getSunDirection () const inline nodiscard
getSunSize()
float MProceduralSkyboxDrawCall::getSunSize () const inline nodiscard
getSunSizeConvergence()
float MProceduralSkyboxDrawCall::getSunSizeConvergence () const inline nodiscard
setAtmosphereThickness()
void MProceduralSkyboxDrawCall::setAtmosphereThickness (float v) inline
setExposure()
void MProceduralSkyboxDrawCall::setExposure (float v) inline
setGroundColor()
void MProceduralSkyboxDrawCall::setGroundColor (const SVector3 & v) inline
setSkyTint()
void MProceduralSkyboxDrawCall::setSkyTint (const SVector3 & v) inline
setSunDirection()
void MProceduralSkyboxDrawCall::setSunDirection (const SVector3 & dir) inline
setSunSize()
void MProceduralSkyboxDrawCall::setSunSize (float v) inline
setSunSizeConvergence()
void MProceduralSkyboxDrawCall::setSunSizeConvergence (float v) inline
setTargetResolution()
void MProceduralSkyboxDrawCall::setTargetResolution (const SVector2 & res) inline
The documentation for this class was generated from the following files:
src/core/engine/skybox/procedural_sky/procedural_skybox_drawcall.h
src/core/engine/skybox/procedural_sky/procedural_skybox_drawcall.cpp