Meteor Engine: MObjectPtr< T > Class Template Reference
MObjectPtr< T > Class Template Reference
#include <objectpointer.h>
Public Member Functions
MObjectPtr (T *obj=nullptr)
~MObjectPtr ()
MObjectPtr (const MObjectPtr &other)
MObjectPtr (MObjectPtr &&other) noexcept
MObjectPtr & operator= (const MObjectPtr &other)
MObjectPtr & operator= (MObjectPtr &&other) noexcept
MObjectPtr & operator= (T *raw)
MObjectPtr & operator= (std::nullptr_t)
T * get () const
T & operator* () const
T * operator-> () const
operator bool () const
bool operator== (std::nullptr_t) const
bool operator!= (std::nullptr_t) const
bool operator== (const MObjectPtr &other) const
bool operator!= (const MObjectPtr &other) const
bool operator== (const T *raw) const
bool operator!= (const T *raw) const
void reset (T *newPtr=nullptr)
Constructor & Destructor Documentation
MObjectPtr() [1/3]
template<typename T> MObjectPtr< T >::MObjectPtr (T * obj = nullptr) inline
References MGarbageCollector::reference().
Referenced by MObjectPtr(), MObjectPtr(), operator!=(), operator=(), operator=(), operator=(), operator=(), and operator==().
~MObjectPtr()
template<typename T> MObjectPtr< T >::~MObjectPtr () inline
MObjectPtr() [2/3]
template<typename T> MObjectPtr< T >::MObjectPtr (const MObjectPtr< T > & other) inline
References MObjectPtr(), and MGarbageCollector::reference().
MObjectPtr() [3/3]
template<typename T> MObjectPtr< T >::MObjectPtr (MObjectPtr< T > && other) inline noexcept
References MObjectPtr().
Member Function Documentation
get()
template<typename T> T * MObjectPtr< T >::get () const inline
operator bool()
template<typename T> MObjectPtr< T >::operator bool () const inline explicit
operator!=() [1/3]
template<typename T> bool MObjectPtr< T >::operator!= (const MObjectPtr< T > & other) const inline
References MObjectPtr().
operator!=() [2/3]
template<typename T> bool MObjectPtr< T >::operator!= (const T * raw) const inline
operator!=() [3/3]
template<typename T> bool MObjectPtr< T >::operator!= (std::nullptr_t) const inline
operator*()
template<typename T> T & MObjectPtr< T >::operator* () const inline
operator->()
template<typename T> T * MObjectPtr< T >::operator-> () const inline
operator=() [1/4]
template<typename T> MObjectPtr & MObjectPtr< T >::operator= (const MObjectPtr< T > & other) inline
References MObjectPtr().
operator=() [2/4]
template<typename T> MObjectPtr & MObjectPtr< T >::operator= (MObjectPtr< T > && other) inline noexcept
References MObjectPtr().
operator=() [3/4]
template<typename T> MObjectPtr & MObjectPtr< T >::operator= (std::nullptr_t) inline
References MObjectPtr().
operator=() [4/4]
template<typename T> MObjectPtr & MObjectPtr< T >::operator= (T * raw) inline
References MObjectPtr().
operator==() [1/3]
template<typename T> bool MObjectPtr< T >::operator== (const MObjectPtr< T > & other) const inline
References MObjectPtr().
operator==() [2/3]
template<typename T> bool MObjectPtr< T >::operator== (const T * raw) const inline
operator==() [3/3]
template<typename T> bool MObjectPtr< T >::operator== (std::nullptr_t) const inline
reset()
template<typename T> void MObjectPtr< T >::reset (T * newPtr = nullptr) inline
The documentation for this class was generated from the following file:
src/core/object/objectpointer.h