Meteor Engine: MSkyboxDrawCall Class Reference
MSkyboxDrawCall Class Reference
#include <skyboxdrawcall.h>
Public Member Functions
MSkyboxDrawCall (TAssetHandle< MCubemapAsset > texture, MShader *shader)
void setCubemapAsset (TAssetHandle< MCubemapAsset > texture)
TAssetHandle< MCubemapAsset > getCubemapAsset () const
void draw () override
int getSortinOrder () override
Public Member Functions inherited from MOpenGlDrawCall
MOpenGlDrawCall ()=default
void setTargetResolution (SVector2 resolution)
Public Member Functions inherited from MDrawCall
MDrawCall ()=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Member Functions inherited from MOpenGlDrawCall
void printOpenGLDrawErrors ()
Protected Attributes inherited from MOpenGlDrawCall
SVector2 resolution
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MSkyboxDrawCall()
MSkyboxDrawCall::MSkyboxDrawCall (TAssetHandle< MCubemapAsset > texture, MShader * shader)
Member Function Documentation
draw()
void MSkyboxDrawCall::draw () override virtual
Reimplemented from MOpenGlDrawCall.
References MViewManagement::getCameras(), MCameraEntity::getProjectionMatrix(), MCameraEntity::getViewMatrix(), MERROR, MWARN, MOpenGlDrawCall::resolution, and SShaderPropertyValue::setMat4Val().
getCubemapAsset()
TAssetHandle< MCubemapAsset > MSkyboxDrawCall::getCubemapAsset () const inline
getSortinOrder()
int MSkyboxDrawCall::getSortinOrder () override virtual
Reimplemented from MDrawCall.
setCubemapAsset()
void MSkyboxDrawCall::setCubemapAsset (TAssetHandle< MCubemapAsset > texture)
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/skybox/skyboxdrawcall.h
src/core/graphics/core/render-pipeline/stages/skybox/skyboxdrawcall.cpp