Meteor Engine: MTextureAsset Class Reference
MTextureAsset Class Reference
#include <textureasset.h>
Public Member Functions
MTextureAsset ()
MTextureAsset (const SString &path)
MTextureAsset (const SString &path, const pugi::xml_node &importSettings)
virtual MTexture * getTexture ()
bool requestReload () override
ETextureFilterMin getFilterMin () const
ETextureFilterMag getFilterMag () const
ETextureWrap getWrapS () const
ETextureWrap getWrapT () const
int getMaxImportSize () const
ETextureCompression getCompression () const
void setFilterMin (ETextureFilterMin f)
void setFilterMag (ETextureFilterMag f)
void setWrapS (ETextureWrap w)
void setWrapT (ETextureWrap w)
void setMaxImportSize (int s)
void setCompression (ETextureCompression c)
void loadImportSettings (const pugi::xml_node &node)
bool saveImportSettings ()
Public Member Functions inherited from MAsset
MAsset (const SString &path)
~MAsset () override=default
SString getPath () const
SString getFullPath () const
bool isValid () const
SString getAssetId () const
void internal_SetAssetId (const SString &assetId)
virtual bool openAsset ()
virtual bool save ()
virtual bool hasDeferredLoad () const override
virtual void deferredAssetLoad (bool forced) override
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MAsset
SString path
SString assetId
bool valid = false
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MTextureAsset() [1/3]
MTextureAsset::MTextureAsset ()
References MAsset::MAsset().
MTextureAsset() [2/3]
MTextureAsset::MTextureAsset (const SString & path) explicit
References MAsset::MAsset(), MAsset::path, and MAsset::valid.
MTextureAsset() [3/3]
MTextureAsset::MTextureAsset (const SString & path, const pugi::xml_node & importSettings)
References loadImportSettings(), MAsset::MAsset(), MAsset::path, and MAsset::valid.
Member Function Documentation
getCompression()
ETextureCompression MTextureAsset::getCompression () const inline
getFilterMag()
ETextureFilterMag MTextureAsset::getFilterMag () const inline
getFilterMin()
ETextureFilterMin MTextureAsset::getFilterMin () const inline
getMaxImportSize()
int MTextureAsset::getMaxImportSize () const inline
getTexture()
MTexture * MTextureAsset::getTexture () virtual
Reimplemented in MCubemapAsset.
getWrapS()
ETextureWrap MTextureAsset::getWrapS () const inline
getWrapT()
ETextureWrap MTextureAsset::getWrapT () const inline
loadImportSettings()
void MTextureAsset::loadImportSettings (const pugi::xml_node & node)
Referenced by MTextureAsset().
requestReload()
bool MTextureAsset::requestReload () override virtual
Implements MAsset.
References MAsset::valid.
saveImportSettings()
bool MTextureAsset::saveImportSettings ()
References SString::c_str(), MERROR, MAsset::path, FileIO::readFile(), and FileIO::writeFile().
setCompression()
void MTextureAsset::setCompression (ETextureCompression c) inline
setFilterMag()
void MTextureAsset::setFilterMag (ETextureFilterMag f) inline
setFilterMin()
void MTextureAsset::setFilterMin (ETextureFilterMin f) inline
setMaxImportSize()
void MTextureAsset::setMaxImportSize (int s) inline
setWrapS()
void MTextureAsset::setWrapS (ETextureWrap w) inline
setWrapT()
void MTextureAsset::setWrapT (ETextureWrap w) inline
The documentation for this class was generated from the following files:
src/core/engine/texture/textureasset.h
src/core/engine/texture/textureasset.cpp