Meteor Engine: SInput Class Reference
SInput Class Reference
#include <input.h>
Static Public Member Functions
static void poll ()
static bool pressedThisFrame (EKeyCode key)
static bool pressedAndReleased (EKeyCode key)
static bool isDown (EKeyCode key)
static bool isCtrlDown ()
static bool isShiftDown ()
static bool isAltDown ()
static const char * getKeyName (EKeyCode key)
Member Function Documentation
getKeyName()
const char * SInput::getKeyName (EKeyCode key) static
References A, Add, Apostrophe, B, Backslash, Backspace, C, Comma, D, Delete, Divide, Down, E, End, Enter, Equal, Escape, F, F1, F10, F11, F12, F13, F14, F15, F2, F3, F4, F5, F6, F7, F8, F9, G, Grave, H, Home, Hyphen, I, Insert, J, K, L, LAlt, LBracket, LControl, Left, LShift, LSystem, M, Menu, Multiply, N, Num0, Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9, Numpad0, Numpad1, Numpad2, Numpad3, Numpad4, Numpad5, Numpad6, Numpad7, Numpad8, Numpad9, O, P, PageDown, PageUp, Pause, Period, Q, R, RAlt, RBracket, RControl, Right, RShift, RSystem, S, Semicolon, Slash, Space, Subtract, T, Tab, U, Up, V, W, X, Y, and Z.
Referenced by MShortcutBinding::getDisplayText().
isAltDown()
bool SInput::isAltDown () static
References isDown(), LAlt, and RAlt.
Referenced by MShortcutListener::poll().
isCtrlDown()
bool SInput::isCtrlDown () static
References isDown(), LControl, and RControl.
Referenced by MShortcutListener::poll().
isDown()
bool SInput::isDown (EKeyCode key) static
Referenced by isAltDown(), isCtrlDown(), and isShiftDown().
isShiftDown()
bool SInput::isShiftDown () static
References isDown(), LShift, and RShift.
Referenced by MShortcutListener::poll().
poll()
void SInput::poll () static
pressedAndReleased()
bool SInput::pressedAndReleased (EKeyCode key) static
pressedThisFrame()
bool SInput::pressedThisFrame (EKeyCode key) static
Referenced by MShortcutListener::poll().
The documentation for this class was generated from the following files:
src/core/engine/input/input.h
src/core/engine/input/input.cpp