Meteor Engine: MAmbientLightEntity Class Reference
MAmbientLightEntity Class Reference
#include <ambient_light.h>
Public Member Functions
MAmbientLightEntity ()
~MAmbientLightEntity () override=default
void prepareLightRender () override
void setColor (const SColor &color) override
SColor getColor () const override
void setIntensity (const float &intensity) override
float getIntensity () const override
void onExit () override
void onDrawGizmo (SVector2 renderResolution) override
Public Member Functions inherited from MLightEntity
ELightType getLightType () const
Public Member Functions inherited from MSpatialEntity
pugi::xml_node serialiseEntity (pugi::xml_node parent) const
void destroy ()
EEntityFlags getEntityFlags () const
void setEntityFlags (EEntityFlags flag)
void setEnabled (bool enable)
bool getEnabled () const
SVector3 getRelativePosition () const
SVector3 getRelativeScale () const
SQuaternion getRelativeRotation () const
SVector3 getWorldPosition () const
SQuaternion getWorldRotation () const
SMatrix4 getModelMatrix () const
SMatrix4 getTransformMatrix () const
void setRelativePosition (const SVector3 &p)
void setRelativeRotation (const SQuaternion &r)
void setRelativeScale (const SVector3 &s)
void setWorldPosition (const SVector3 &worldPosition)
void setWorldRotation (const SQuaternion &worldRotation)
SVector3 getForwardVector () const
SVector3 getRightVector () const
SVector3 getUpVector () const
MSpatialEntity * getParent ()
std::vector< MSpatialEntity * > & getChildren ()
void setParentScene (MScene *scene)
void setParent (MSpatialEntity *newParent)
void addChild (MSpatialEntity *entity)
void removeChild (MSpatialEntity *entity)
void insertChildAt (MSpatialEntity *entity, int index)
template<typename T>
T * find (const SString &searchName)
void updateTransforms ()
virtual void onCreate ()
virtual void onStart ()
virtual void onUpdate (float deltaTime)
bool hasStarted () const
bool getCanTick () const
void setCanTick (bool tick)
~MSpatialEntity () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MSpatialEntity
static MSpatialEntity * createInstance (const SString &name={})
template<typename T>
static T * createInstance (const SString &name, MScene *ownerScene=nullptr)
static MSpatialEntity * deserialiseEntity (const pugi::xml_node &node)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Member Functions inherited from MSpatialEntity
void onSerialise (pugi::xml_node &node) override
void onDeserialise (const pugi::xml_node &node) override
MSpatialEntity ()
MSpatialEntity (MSpatialEntity *parent)
Protected Attributes inherited from MLightEntity
ELightType lightType = ELightType::Ambient
Protected Attributes inherited from MSpatialEntity
SVector3 relativePosition = SVector3(0.0f)
SQuaternion relativeRotation = glm::identity<SQuaternion>()
SVector3 relativeScale = SVector3(1.0f)
SMatrix4 modelMatrix = glm::identity<SMatrix4>()
MSpatialEntity * parent = nullptr
std::vector< MSpatialEntity * > children
bool enabled = true
EEntityFlags flags = EEntityFlags::Default
MScene * ownerScene = nullptr
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MAmbientLightEntity()
MAmbientLightEntity::MAmbientLightEntity ()
References Ambient, MLightSystemManager::getInstance(), MLightEntity::lightType, MERROR, MLightSystemManager::registerLight(), and STR.
Referenced by ~MAmbientLightEntity().
~MAmbientLightEntity()
MAmbientLightEntity::~MAmbientLightEntity () override default
References MAmbientLightEntity().
Member Function Documentation
getColor()
SColor MAmbientLightEntity::getColor () const override virtual
Implements MLightEntity.
getIntensity()
float MAmbientLightEntity::getIntensity () const override virtual
Implements MLightEntity.
onDrawGizmo()
void MAmbientLightEntity::onDrawGizmo (SVector2 renderResolution) override virtual
Reimplemented from MSpatialEntity.
References MGizmos::drawTextureRect(), MEngineSubsystemRegistry::getSubsystem(), MSpatialEntity::getWorldPosition(), and SEditorAssetPaths::HIGHRES_TEX_GIZMOS_AMBIENT_LIGHT.
onExit()
void MAmbientLightEntity::onExit () override virtual
Reimplemented from MSpatialEntity.
References MLightSystemManager::getInstance(), MSpatialEntity::onExit(), and MLightSystemManager::unregisterLight().
prepareLightRender()
void MAmbientLightEntity::prepareLightRender () override virtual
Implements MLightEntity.
References MSpatialEntity::getEnabled(), and LIGHT_INDEX_AMBIENT.
setColor()
void MAmbientLightEntity::setColor (const SColor & color) override virtual
Implements MLightEntity.
References SColor::b, SColor::g, and SColor::r.
setIntensity()
void MAmbientLightEntity::setIntensity (const float & intensity) override virtual
Implements MLightEntity.
The documentation for this class was generated from the following files:
src/core/engine/lighting/ambient/ambient_light.h
src/core/engine/lighting/ambient/ambient_light.cpp