Meteor Engine: MProceduralSkyboxEntity Class Reference
MProceduralSkyboxEntity Class Reference
#include <procedural_sky.h>
Public Member Functions
MProceduralSkyboxEntity ()
~MProceduralSkyboxEntity () override
void submitRenderItem (IRenderItemCollector *collector) override
bool canDraw () override
void onExit () override
void onUpdate (float deltaTime) override
void onDrawGizmo (SVector2 res) override
void setSunAngles (float elevationDeg, float azimuthDeg)
void setSunDirection (const SVector3 &dir)
SVector3 getSunDirection () const
void setDayNightCycleSpeed (float cyclesPerSec)
float getDayNightCycleSpeed () const
void setSunSize (float v)
void setSunSizeConvergence (float v)
void setAtmosphereThickness (float v)
void setSkyTint (const SVector3 &v)
void setGroundColor (const SVector3 &v)
void setExposure (float v)
float getSunSize () const
float getSunSizeConvergence () const
float getAtmosphereThickness () const
SVector3 getSkyTint () const
SVector3 getGroundColor () const
float getExposure () const
Public Member Functions inherited from MSpatialEntity
pugi::xml_node serialiseEntity (pugi::xml_node parent) const
void destroy ()
EEntityFlags getEntityFlags () const
void setEntityFlags (EEntityFlags flag)
void setEnabled (bool enable)
bool getEnabled () const
SVector3 getRelativePosition () const
SVector3 getRelativeScale () const
SQuaternion getRelativeRotation () const
SVector3 getWorldPosition () const
SQuaternion getWorldRotation () const
SMatrix4 getModelMatrix () const
SMatrix4 getTransformMatrix () const
void setRelativePosition (const SVector3 &p)
void setRelativeRotation (const SQuaternion &r)
void setRelativeScale (const SVector3 &s)
void setWorldPosition (const SVector3 &worldPosition)
void setWorldRotation (const SQuaternion &worldRotation)
SVector3 getForwardVector () const
SVector3 getRightVector () const
SVector3 getUpVector () const
MSpatialEntity * getParent ()
std::vector< MSpatialEntity * > & getChildren ()
void setParentScene (MScene *scene)
void setParent (MSpatialEntity *newParent)
void addChild (MSpatialEntity *entity)
void removeChild (MSpatialEntity *entity)
void insertChildAt (MSpatialEntity *entity, int index)
template<typename T>
T * find (const SString &searchName)
void updateTransforms ()
virtual void onCreate ()
virtual void onStart ()
bool hasStarted () const
bool getCanTick () const
void setCanTick (bool tick)
~MSpatialEntity () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IMeteorDrawable
virtual ~IMeteorDrawable ()=default
Protected Member Functions
void onDeserialise (const pugi::xml_node &node) override
Protected Member Functions inherited from MSpatialEntity
void onSerialise (pugi::xml_node &node) override
void onDeserialise (const pugi::xml_node &node) override
MSpatialEntity ()
MSpatialEntity (MSpatialEntity *parent)
Additional Inherited Members
Static Public Member Functions inherited from MSpatialEntity
static MSpatialEntity * createInstance (const SString &name={})
template<typename T>
static T * createInstance (const SString &name, MScene *ownerScene=nullptr)
static MSpatialEntity * deserialiseEntity (const pugi::xml_node &node)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MSpatialEntity
SVector3 relativePosition = SVector3(0.0f)
SQuaternion relativeRotation = glm::identity<SQuaternion>()
SVector3 relativeScale = SVector3(1.0f)
SMatrix4 modelMatrix = glm::identity<SMatrix4>()
MSpatialEntity * parent = nullptr
std::vector< MSpatialEntity * > children
bool enabled = true
EEntityFlags flags = EEntityFlags::Default
MScene * ownerScene = nullptr
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MProceduralSkyboxEntity()
MProceduralSkyboxEntity::MProceduralSkyboxEntity ()
References MProceduralSkyboxQueue::add(), MEngineSubsystemRegistry::getSubsystem(), MERROR, MProceduralSkyboxEntity(), MObject::name, and MSpatialEntity::setCanTick().
Referenced by MProceduralSkyboxEntity().
~MProceduralSkyboxEntity()
MProceduralSkyboxEntity::~MProceduralSkyboxEntity () override
References MProceduralSkyboxQueue::remove().
Member Function Documentation
canDraw()
bool MProceduralSkyboxEntity::canDraw () inline override virtual
Implements IMeteorDrawable.
References MSpatialEntity::getEnabled().
getAtmosphereThickness()
float MProceduralSkyboxEntity::getAtmosphereThickness () const nodiscard
getDayNightCycleSpeed()
float MProceduralSkyboxEntity::getDayNightCycleSpeed () const inline
getExposure()
float MProceduralSkyboxEntity::getExposure () const nodiscard
getGroundColor()
SVector3 MProceduralSkyboxEntity::getGroundColor () const nodiscard
getSkyTint()
SVector3 MProceduralSkyboxEntity::getSkyTint () const nodiscard
getSunDirection()
SVector3 MProceduralSkyboxEntity::getSunDirection () const nodiscard
getSunSize()
float MProceduralSkyboxEntity::getSunSize () const nodiscard
getSunSizeConvergence()
float MProceduralSkyboxEntity::getSunSizeConvergence () const nodiscard
onDeserialise()
void MProceduralSkyboxEntity::onDeserialise (const pugi::xml_node & node) override protected
References MSpatialEntity::onDeserialise().
onDrawGizmo()
void MProceduralSkyboxEntity::onDrawGizmo (SVector2 res) override virtual
Reimplemented from MSpatialEntity.
References MGizmos::drawTextureRect(), MEngineSubsystemRegistry::getSubsystem(), MSpatialEntity::getWorldPosition(), and SEditorAssetPaths::HIGHRES_TEX_GIZMOS_PROC_SKYBOX.
onExit()
void MProceduralSkyboxEntity::onExit () override virtual
Reimplemented from MSpatialEntity.
References MSpatialEntity::onExit(), and MProceduralSkyboxQueue::remove().
onUpdate()
void MProceduralSkyboxEntity::onUpdate (float deltaTime) override virtual
Reimplemented from MSpatialEntity.
References MSpatialEntity::onUpdate().
setAtmosphereThickness()
void MProceduralSkyboxEntity::setAtmosphereThickness (float v)
setDayNightCycleSpeed()
void MProceduralSkyboxEntity::setDayNightCycleSpeed (float cyclesPerSec) inline
setExposure()
void MProceduralSkyboxEntity::setExposure (float v)
setGroundColor()
void MProceduralSkyboxEntity::setGroundColor (const SVector3 & v)
setSkyTint()
void MProceduralSkyboxEntity::setSkyTint (const SVector3 & v)
setSunAngles()
void MProceduralSkyboxEntity::setSunAngles (float elevationDeg, float azimuthDeg)
setSunDirection()
void MProceduralSkyboxEntity::setSunDirection (const SVector3 & dir)
setSunSize()
void MProceduralSkyboxEntity::setSunSize (float v)
setSunSizeConvergence()
void MProceduralSkyboxEntity::setSunSizeConvergence (float v)
submitRenderItem()
void MProceduralSkyboxEntity::submitRenderItem (IRenderItemCollector * collector) override virtual
Implements IMeteorDrawable.
The documentation for this class was generated from the following files:
src/core/engine/skybox/procedural_sky/procedural_sky.h
src/core/engine/skybox/procedural_sky/procedural_sky.cpp