Meteor Engine: MMaterial Class Reference
MMaterial Class Reference
#include <material.h>
Public Types
enum class ShadingMode { Lit , Unlit }
Public Member Functions
MMaterial (MShader *shader, ShadingMode mode=ShadingMode::Lit)
~MMaterial () override=default
void bindMaterial () const
const std::map< SString, SShaderPropertyValue > & getProperties () const
void setProperty (const SString &name, const SShaderPropertyValue &value)
MMaterial * clone () const
MShader * getShader () const
void updateShader (MShader *newShader, ShadingMode newMode)
ShadingMode getShadingMode () const
bool isValid () const
bool isUnlit () const
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Enumeration Documentation
ShadingMode
enum class MMaterial::ShadingMode strong
Enumerator
Lit
Unlit
Constructor & Destructor Documentation
MMaterial()
MMaterial::MMaterial (MShader * shader, ShadingMode mode = ShadingMode::Lit) explicit
References MShader::getProperties(), MERROR, MObject::MObject(), and MObject::name.
Referenced by clone(), and ~MMaterial().
~MMaterial()
MMaterial::~MMaterial () override default
References MMaterial(), and MObject::name.
Member Function Documentation
bindMaterial()
void MMaterial::bindMaterial () const
References MERROR.
clone()
MMaterial * MMaterial::clone () const
References MMaterial().
getProperties()
const std::map< SString, SShaderPropertyValue > & MMaterial::getProperties () const nodiscard
Referenced by MMaterialPropertyControl::draw().
getShader()
MShader * MMaterial::getShader () const inline nodiscard
getShadingMode()
ShadingMode MMaterial::getShadingMode () const inline nodiscard
isUnlit()
bool MMaterial::isUnlit () const inline nodiscard
References Unlit.
isValid()
bool MMaterial::isValid () const inline nodiscard
setProperty()
void MMaterial::setProperty (const SString & name, const SShaderPropertyValue & value)
References MObject::name.
updateShader()
void MMaterial::updateShader (MShader * newShader, ShadingMode newMode) inline
References MShader::getProperties().
The documentation for this class was generated from the following files:
src/core/graphics/core/material/material.h
src/core/graphics/core/material/material.cpp