Meteor Engine: MSceneIO Class Reference
MSceneIO Class Reference
#include <scene_io.h>
Static Public Member Functions
static bool saveCurrentScene ()
static bool loadScene (const SString &filePath)
static bool newScene ()
static SString getCurrentPath ()
static void setCurrentPath (const SString &path)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
getCurrentPath()
SString MSceneIO::getCurrentPath () inline static nodiscard
loadScene()
bool MSceneIO::loadScene (const SString & filePath) static
References SString::empty(), MSceneManager::getSceneManagerInstance(), MEditorSceneManager::loadScene(), and MERROR.
Referenced by MOpenSceneMenubarItem::drawPopup().
newScene()
bool MSceneIO::newScene () static
References MSceneManager::getSceneManagerInstance(), MSceneManager::loadEmptyScene(), and MLOG.
Referenced by MCreateEmptySceneMenubarItem::onSelect().
saveCurrentScene()
bool MSceneIO::saveCurrentScene () static
References MSceneManager::getSceneManagerInstance(), and MEditorSceneManager::saveCurrentScene().
setCurrentPath()
void MSceneIO::setCurrentPath (const SString & path) inline static
The documentation for this class was generated from the following files:
src/editor/helper/scene_io.h
src/editor/helper/scene_io.cpp