Meteor Engine: MLightSystemManager Class Reference
MLightSystemManager Class Reference
#include <lighting_system_manager.h>
Public Member Functions
void registerLight (MLightEntity *light)
void unregisterLight (MLightEntity *light)
void prepareLights ()
void prepareDynamicLights (const AABB &bounds)
void requestLightSceneRebuild ()
bool isDirectionalShadowEnabled () const
bool isDirectionalSmoothShadow () const
MLightEntity * getDirectionalLight () const
const std::vector< MDynamicLight * > & getDynamicLights () const
Static Public Member Functions
static MLightSystemManager * getInstance ()
Member Function Documentation
getDirectionalLight()
MLightEntity * MLightSystemManager::getDirectionalLight () const inline
getDynamicLights()
const std::vector< MDynamicLight * > & MLightSystemManager::getDynamicLights () const inline
getInstance()
MLightSystemManager * MLightSystemManager::getInstance () static
Referenced by MSceneManager::closeActiveScene(), MAmbientLightEntity::MAmbientLightEntity(), MDirectionalLight::MDirectionalLight(), MPointLight::MPointLight(), MSpotLight::MSpotLight(), MAmbientLightEntity::onExit(), MDirectionalLight::onExit(), MPointLight::onExit(), MSpotLight::onExit(), MDynamicLight::onUpdate(), MOpaqueStage::preRender(), MLightingStage::render(), MOpaqueStage::render(), and MShadowStage::render().
isDirectionalShadowEnabled()
bool MLightSystemManager::isDirectionalShadowEnabled () const inline
References MDirectionalLight::getCastsShadow().
isDirectionalSmoothShadow()
bool MLightSystemManager::isDirectionalSmoothShadow () const inline
References MDirectionalLight::getSmoothShadow().
prepareDynamicLights()
void MLightSystemManager::prepareDynamicLights (const AABB & bounds)
References LIGHT_INDEX_DYNAMIC, and None.
Referenced by MOpaqueStage::render().
prepareLights()
void MLightSystemManager::prepareLights ()
Referenced by MOpaqueStage::preRender().
registerLight()
void MLightSystemManager::registerLight (MLightEntity * light)
References Ambient, Directional, MLightEntity::getLightType(), Point, and Spot.
Referenced by MAmbientLightEntity::MAmbientLightEntity(), MDirectionalLight::MDirectionalLight(), MPointLight::MPointLight(), and MSpotLight::MSpotLight().
requestLightSceneRebuild()
void MLightSystemManager::requestLightSceneRebuild ()
Referenced by MDynamicLight::onUpdate().
unregisterLight()
void MLightSystemManager::unregisterLight (MLightEntity * light)
References Ambient, Directional, MLightEntity::getLightType(), Point, and Spot.
Referenced by MAmbientLightEntity::onExit(), MDirectionalLight::onExit(), MPointLight::onExit(), and MSpotLight::onExit().
The documentation for this class was generated from the following files:
src/core/graphics/core/render-pipeline/stages/lighting/lighting_system_manager.h
src/core/graphics/core/render-pipeline/stages/lighting/lighting_system_manager.cpp