Meteor Engine: MAudioSource Class Reference
MAudioSource Class Reference
#include <audio_source_entity.h>
Public Member Functions
MAudioSource ()=default
~MAudioSource () override=default
void onCreate () override
void onStart () override
void onUpdate (float deltaTime) override
void onExit () override
void onDrawGizmo (SVector2 renderResolution) override
void setClip (TAssetHandle< MAudioClipAsset > clip)
Set clip to play – accepts a handle; TAssetRef converts implicitly.
TAssetRef< MAudioClipAsset > getClip () const
Get current clip reference (carries both GUID and path).
void play ()
Play this source.
void stop ()
Stop this source.
void playOneShot (TAssetHandle< MAudioClipAsset > clip)
Play this clip as oneshot.
bool getLoop () const
void setLoop (bool v)
float getVolume () const
void setVolume (float v)
float getPitch () const
void setPitch (float v)
bool getUseSpatial () const
void setUseSpatial (bool v)
float getRollOff () const
void setRollOff (float v)
float getMinDist () const
void setMinDist (float v)
float getMaxDist () const
void setMaxDist (float v)
float getDopplerStrength () const
void setDopplerStrength (float v)
Public Member Functions inherited from MSpatialEntity
pugi::xml_node serialiseEntity (pugi::xml_node parent) const
void destroy ()
EEntityFlags getEntityFlags () const
void setEntityFlags (EEntityFlags flag)
void setEnabled (bool enable)
bool getEnabled () const
SVector3 getRelativePosition () const
SVector3 getRelativeScale () const
SQuaternion getRelativeRotation () const
SVector3 getWorldPosition () const
SQuaternion getWorldRotation () const
SMatrix4 getModelMatrix () const
SMatrix4 getTransformMatrix () const
void setRelativePosition (const SVector3 &p)
void setRelativeRotation (const SQuaternion &r)
void setRelativeScale (const SVector3 &s)
void setWorldPosition (const SVector3 &worldPosition)
void setWorldRotation (const SQuaternion &worldRotation)
SVector3 getForwardVector () const
SVector3 getRightVector () const
SVector3 getUpVector () const
MSpatialEntity * getParent ()
std::vector< MSpatialEntity * > & getChildren ()
void setParentScene (MScene *scene)
void setParent (MSpatialEntity *newParent)
void addChild (MSpatialEntity *entity)
void removeChild (MSpatialEntity *entity)
void insertChildAt (MSpatialEntity *entity, int index)
template<typename T>
T * find (const SString &searchName)
void updateTransforms ()
bool hasStarted () const
bool getCanTick () const
void setCanTick (bool tick)
~MSpatialEntity () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Additional Inherited Members
Static Public Member Functions inherited from MSpatialEntity
static MSpatialEntity * createInstance (const SString &name={})
template<typename T>
static T * createInstance (const SString &name, MScene *ownerScene=nullptr)
static MSpatialEntity * deserialiseEntity (const pugi::xml_node &node)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Member Functions inherited from MSpatialEntity
void onSerialise (pugi::xml_node &node) override
void onDeserialise (const pugi::xml_node &node) override
MSpatialEntity ()
MSpatialEntity (MSpatialEntity *parent)
Protected Attributes inherited from MSpatialEntity
SVector3 relativePosition = SVector3(0.0f)
SQuaternion relativeRotation = glm::identity<SQuaternion>()
SVector3 relativeScale = SVector3(1.0f)
SMatrix4 modelMatrix = glm::identity<SMatrix4>()
MSpatialEntity * parent = nullptr
std::vector< MSpatialEntity * > children
bool enabled = true
EEntityFlags flags = EEntityFlags::Default
MScene * ownerScene = nullptr
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MAudioSource()
MAudioSource::MAudioSource () default
Referenced by onCreate().
~MAudioSource()
MAudioSource::~MAudioSource () override default
Member Function Documentation
getClip()
TAssetRef< MAudioClipAsset > MAudioSource::getClip () const inline
Get current clip reference (carries both GUID and path).
getDopplerStrength()
float MAudioSource::getDopplerStrength () const inline
getLoop()
bool MAudioSource::getLoop () const inline
getMaxDist()
float MAudioSource::getMaxDist () const inline
getMinDist()
float MAudioSource::getMinDist () const inline
getPitch()
float MAudioSource::getPitch () const inline
getRollOff()
float MAudioSource::getRollOff () const inline
getUseSpatial()
bool MAudioSource::getUseSpatial () const inline
getVolume()
float MAudioSource::getVolume () const inline
onCreate()
void MAudioSource::onCreate () override virtual
Reimplemented from MSpatialEntity.
References MEngineSubsystemRegistry::getSubsystem(), MAudioSource(), MERROR, onCreate(), MSpatialEntity::onCreate(), and MSpatialEntity::setCanTick().
Referenced by onCreate().
onDrawGizmo()
void MAudioSource::onDrawGizmo (SVector2 renderResolution) override virtual
Reimplemented from MSpatialEntity.
References MGizmos::drawTextureRect(), MGizmos::drawWireSphere(), MEngineSubsystemRegistry::getSubsystem(), MSpatialEntity::getWorldPosition(), SEditorAssetPaths::HIGHRES_TEX_GIZMOS_AUDIO_SOURCE_2D, and SEditorAssetPaths::HIGHRES_TEX_GIZMOS_AUDIO_SOURCE_3D.
onExit()
void MAudioSource::onExit () override virtual
Reimplemented from MSpatialEntity.
References MSpatialEntity::onExit().
onStart()
void MAudioSource::onStart () override virtual
Reimplemented from MSpatialEntity.
References MSpatialEntity::onStart().
onUpdate()
void MAudioSource::onUpdate (float deltaTime) override virtual
Reimplemented from MSpatialEntity.
References MSpatialEntity::getForwardVector(), MSpatialEntity::getWorldPosition(), and MSpatialEntity::onUpdate().
play()
void MAudioSource::play ()
Play this source.
playOneShot()
void MAudioSource::playOneShot (TAssetHandle< MAudioClipAsset > clip)
Play this clip as oneshot.
References TAssetHandle< T >::get(), MAudioClipAsset::getAudioClip(), and TAssetHandle< T >::isValid().
setClip()
void MAudioSource::setClip (TAssetHandle< MAudioClipAsset > clip)
Set clip to play – accepts a handle; TAssetRef converts implicitly.
References TAssetHandle< T >::get(), MAudioClipAsset::getAudioClip(), and TAssetHandle< T >::isValid().
setDopplerStrength()
void MAudioSource::setDopplerStrength (float v) inline
setLoop()
void MAudioSource::setLoop (bool v) inline
setMaxDist()
void MAudioSource::setMaxDist (float v) inline
setMinDist()
void MAudioSource::setMinDist (float v) inline
setPitch()
void MAudioSource::setPitch (float v) inline
setRollOff()
void MAudioSource::setRollOff (float v) inline
setUseSpatial()
void MAudioSource::setUseSpatial (bool v) inline
setVolume()
void MAudioSource::setVolume (float v) inline
stop()
void MAudioSource::stop ()
Stop this source.
The documentation for this class was generated from the following files:
src/core/engine/audio/audio_entity/audio_source_entity.h
src/core/engine/audio/audio_entity/audio_source_entity.cpp