Meteor Engine: MGizmos Class Reference
MGizmos Class Reference
#include <gizmos.h>
Static Public Member Functions
static void drawTextureRect (const SVector3 &position, const SVector2 &halfExtents, MTexture *texture)
static void drawWireCube (SVector3 position, SVector3 halfExtents, SColor color, float thickness)
static void drawWireSphere (SVector3 position, float radius, SColor color, float thickness)
static void drawRay (const SVector3 &origin, const SVector3 &direction, const float &length, const SColor &color, const float &thickness)
static void drawLine (const SVector3 &start, const SVector3 &end, const SColor &color, const float &thickness, bool ignoreZDepth=false)
static void drawWireFrustum (const glm::mat4 &viewMatrix, const glm::mat4 &projectionMatrix, SColor color, float thickness)
static void enableGizmos (bool enable)
static void requestGizmoDraws ()
static void recursiveGizmoDraws (MSpatialEntity *entity)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
drawLine()
void MGizmos::drawLine (const SVector3 & start, const SVector3 & end, const SColor & color, const float & thickness, bool ignoreZDepth = false) static
References SColor::a, SColor::b, SColor::g, MShaderAsset::getShader(), MEngineSubsystemRegistry::getSubsystem(), SColor::r, SShaderPropertyValue::setMat4Val(), and SShaderPropertyValue::setVec4Val().
Referenced by drawRay(), drawWireCube(), drawWireFrustum(), and drawWireSphere().
drawRay()
void MGizmos::drawRay (const SVector3 & origin, const SVector3 & direction, const float & length, const SColor & color, const float & thickness) static
References drawLine().
Referenced by MDirectionalLight::onDrawGizmo().
drawTextureRect()
void MGizmos::drawTextureRect (const SVector3 & position, const SVector2 & halfExtents, MTexture * texture) static
References MTexture::bind(), MEngineSubsystemRegistry::getSubsystem(), MLOG, and SShaderPropertyValue::setMat4Val().
Referenced by MAmbientLightEntity::onDrawGizmo(), MAudioListener::onDrawGizmo(), MAudioSource::onDrawGizmo(), MCameraEntity::onDrawGizmo(), MDirectionalLight::onDrawGizmo(), MPointLight::onDrawGizmo(), MProceduralSkyboxEntity::onDrawGizmo(), MSkyboxEntity::onDrawGizmo(), and MSpotLight::onDrawGizmo().
drawWireCube()
void MGizmos::drawWireCube (SVector3 position, SVector3 halfExtents, SColor color, float thickness) static
References drawLine().
drawWireFrustum()
void MGizmos::drawWireFrustum (const glm::mat4 & viewMatrix, const glm::mat4 & projectionMatrix, SColor color, float thickness) static
References drawLine().
Referenced by MCameraEntity::onDrawGizmo().
drawWireSphere()
void MGizmos::drawWireSphere (SVector3 position, float radius, SColor color, float thickness) static
References drawLine().
Referenced by MAudioSource::onDrawGizmo(), and MPointLight::onDrawGizmo().
enableGizmos()
void MGizmos::enableGizmos (bool enable) static
Referenced by MEditorApplication::initialise().
recursiveGizmoDraws()
void MGizmos::recursiveGizmoDraws (MSpatialEntity * entity) static
References MSpatialEntity::getChildren(), MSpatialEntity::getEnabled(), MSpatialEntity::onDrawGizmo(), and recursiveGizmoDraws().
Referenced by recursiveGizmoDraws(), and requestGizmoDraws().
requestGizmoDraws()
void MGizmos::requestGizmoDraws () static
References MSceneManager::getSceneManagerInstance(), and recursiveGizmoDraws().
Referenced by MGizmoStage::render().
The documentation for this class was generated from the following files:
src/core/engine/gizmos/gizmos.h
src/core/engine/gizmos/gizmos.cpp