Meteor Engine: IRenderPipeline Class Reference
IRenderPipeline Class Reference abstract
#include <render_pipeline_interface.h>
Public Member Functions
virtual ~IRenderPipeline ()=default
virtual void init ()=0
virtual void cleanup ()=0
template<typename T>
bool addStage ()
virtual void preRender ()=0
virtual void render ()=0
virtual void postRender ()=0
virtual SVector2 getRenderResolution ()=0
virtual void setRenderBuffer (SRenderBuffer *buffer)=0
virtual SRenderBuffer * getRenderBuffer ()=0
virtual MBufferRegistery & getBufferRegistry ()=0
virtual const std::vector< SRenderItem > & getRenderItems () const =0
virtual uint32_t getCompositeFlags () const =0
virtual void addCompositeFlag (ECompositeFlags flag)=0
virtual void removeCompositeFlag (ECompositeFlags flag)=0
virtual void clearCompositeFlags ()=0
Protected Attributes
std::vector< IRenderStage * > renderStages
Constructor & Destructor Documentation
~IRenderPipeline()
virtual IRenderPipeline::~IRenderPipeline () virtual default
Member Function Documentation
addCompositeFlag()
virtual void IRenderPipeline::addCompositeFlag (ECompositeFlags flag) pure virtual
Implemented in MRenderPipeline.
Referenced by MDepthRenderStage::render(), MLightingStage::render(), and MOpaqueStage::render().
addStage()
template<typename T> bool IRenderPipeline::addStage () inline
References IRenderStage::init(), renderStages, and T.
Referenced by MRenderPipeline::init().
cleanup()
virtual void IRenderPipeline::cleanup () pure virtual
Implemented in MRenderPipeline.
clearCompositeFlags()
virtual void IRenderPipeline::clearCompositeFlags () pure virtual
Implemented in MRenderPipeline.
getBufferRegistry()
virtual MBufferRegistery & IRenderPipeline::getBufferRegistry () pure virtual
Implemented in MRenderPipeline.
Referenced by MDepthRenderStage::cleanup(), MDepthRenderStage::init(), MLightingStage::init(), MOpaqueStage::init(), MProceduralSkyboxStage::init(), MShadowStage::init(), MSkyboxStage::init(), MProceduralSkyboxStage::preRender(), MSkyboxStage::preRender(), MClearStage::render(), MGizmoStage::render(), and MLightingStage::render().
getCompositeFlags()
virtual uint32_t IRenderPipeline::getCompositeFlags () const pure virtual
Implemented in MRenderPipeline.
Referenced by MCompositeStage::render(), and MLightingStage::render().
getRenderBuffer()
virtual SRenderBuffer * IRenderPipeline::getRenderBuffer () pure virtual
Implemented in MRenderPipeline.
Referenced by MCompositeStage::render(), and MGizmoStage::render().
getRenderItems()
virtual const std::vector< SRenderItem > & IRenderPipeline::getRenderItems () const pure virtual
Implemented in MRenderPipeline.
Referenced by MDepthRenderStage::render(), MLightingStage::render(), and MOpaqueStage::render().
getRenderResolution()
virtual SVector2 IRenderPipeline::getRenderResolution () pure virtual
Implemented in MRenderPipeline.
Referenced by MClearStage::render(), MCompositeStage::render(), MDepthRenderStage::render(), MGizmoStage::render(), MLightingStage::render(), MOpaqueStage::render(), MProceduralSkyboxStage::render(), and MSkyboxStage::render().
init()
virtual void IRenderPipeline::init () pure virtual
Implemented in MRenderPipeline.
postRender()
virtual void IRenderPipeline::postRender () pure virtual
Implemented in MRenderPipeline.
preRender()
virtual void IRenderPipeline::preRender () pure virtual
Implemented in MRenderPipeline.
removeCompositeFlag()
virtual void IRenderPipeline::removeCompositeFlag (ECompositeFlags flag) pure virtual
Implemented in MRenderPipeline.
render()
virtual void IRenderPipeline::render () pure virtual
Implemented in MRenderPipeline.
setRenderBuffer()
virtual void IRenderPipeline::setRenderBuffer (SRenderBuffer * buffer) pure virtual
Implemented in MRenderPipeline.
Member Data Documentation
renderStages
std::vector<IRenderStage*> IRenderPipeline::renderStages protected
Referenced by addStage(), MRenderPipeline::cleanup(), MRenderPipeline::postRender(), MRenderPipeline::preRender(), and MRenderPipeline::render().
The documentation for this class was generated from the following file:
src/core/graphics/core/render-pipeline/interfaces/render_pipeline_interface.h