Meteor Engine: MAssetReferenceControl Class Reference
MAssetReferenceControl Class Reference
#include <asset_reference_controls.h>
Public Member Functions
MAssetReferenceControl ()=default
MAssetReferenceControl (TAssetHandle< MAsset > asset)
TAssetHandle< MAsset > getAssetReference () const
void setAssetReference (TAssetHandle< MAsset > asset)
bool drawControl (const SString &label)
bool drawCompactControl (const SString &label)
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Attributes
std::function< bool(TAssetHandle< MAsset > asset)> canAcceptAssetFuncCallback
Static Public Attributes
static const SString ASSET_REF_TARGET_KEY = "_AssetFileRef"
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Constructor & Destructor Documentation
MAssetReferenceControl() [1/2]
MAssetReferenceControl::MAssetReferenceControl () default
MAssetReferenceControl() [2/2]
MAssetReferenceControl::MAssetReferenceControl (TAssetHandle< MAsset > asset) explicit
References canAcceptAssetFuncCallback, and TAssetHandle< T >::getAssetId().
Member Function Documentation
drawCompactControl()
bool MAssetReferenceControl::drawCompactControl (const SString & label)
References ASSET_REF_TARGET_KEY, canAcceptAssetFuncCallback, IAssetManagerSubsystem::getAssetById(), getAssetReference(), MObject::getGUID(), MEngineSubsystemRegistry::getSubsystem(), and MEditorAssetManager::pingAsset().
Referenced by drawControl().
drawControl()
bool MAssetReferenceControl::drawControl (const SString & label)
References drawCompactControl().
getAssetReference()
TAssetHandle< MAsset > MAssetReferenceControl::getAssetReference () const
References MEngineSubsystemRegistry::getSubsystem().
Referenced by drawCompactControl().
setAssetReference()
void MAssetReferenceControl::setAssetReference (TAssetHandle< MAsset > asset)
References TAssetHandle< T >::getAssetId().
Member Data Documentation
ASSET_REF_TARGET_KEY
const SString MAssetReferenceControl::ASSET_REF_TARGET_KEY = "_AssetFileRef" static
Referenced by drawCompactControl(), and MEditorSceneViewWindow::onGui().
canAcceptAssetFuncCallback
std::function<bool(TAssetHandle<MAsset> asset)> MAssetReferenceControl::canAcceptAssetFuncCallback
Referenced by drawCompactControl(), and MAssetReferenceControl().
The documentation for this class was generated from the following files:
src/editor/editorwindows/inspectordrawer/controls/asset_reference_controls.h
src/editor/editorwindows/inspectordrawer/controls/asset_reference_controls.cpp