Meteor Engine: FileIO Class Reference
FileIO Class Reference
#include <fileio.h>
Static Public Member Functions
static bool hasFile (const SString &path)
static bool readFile (const SString &path, SString &data)
static bool writeFile (const SString &path, const SString &data)
static SString getFileExtension (const SString &path)
static SString getWorkingDir ()
static SString getFileName (const SString &path)
static SString getFileNameWithoutExtension (const SString &path)
static SString getParentDirectory (const SString &path)
static SString changeExtension (const SString &path, const SString &newExt)
static SString joinPath (const SString &base, const SString &relative)
static SString normalizePath (const SString &path)
static int64_t getFileSize (const SString &path)
static bool deleteFile (const SString &path)
static bool copyFile (const SString &src, const SString &dst)
static bool createDirectory (const SString &path)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Additional Inherited Members
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
changeExtension()
SString FileIO::changeExtension (const SString & path, const SString & newExt) static
copyFile()
bool FileIO::copyFile (const SString & src, const SString & dst) static
createDirectory()
bool FileIO::createDirectory (const SString & path) static
deleteFile()
bool FileIO::deleteFile (const SString & path) static
getFileExtension()
SString FileIO::getFileExtension (const SString & path) static
References SString::length().
Referenced by MAssetManager::loadAsset(), and MAssetManager::loadAssetRecursive().
getFileName()
SString FileIO::getFileName (const SString & path) static
Referenced by getFileNameWithoutExtension(), and MAudioClipAsset::MAudioClipAsset().
getFileNameWithoutExtension()
SString FileIO::getFileNameWithoutExtension (const SString & path) static
References getFileName(), and MObject::name.
getFileSize()
int64_t FileIO::getFileSize (const SString & path) static
getParentDirectory()
SString FileIO::getParentDirectory (const SString & path) static
getWorkingDir()
SString FileIO::getWorkingDir () static
Referenced by MAsset::getFullPath().
hasFile()
bool FileIO::hasFile (const SString & path) static
References SString::c_str().
Referenced by MMaterialAsset::createNewMaterial(), MAssetManager::hasMetaData(), and MEngineStatics::loadEngineSettings().
joinPath()
SString FileIO::joinPath (const SString & base, const SString & relative) static
References SString::empty().
normalizePath()
SString FileIO::normalizePath (const SString & path) static
readFile()
bool FileIO::readFile (const SString & path, SString & data) static
References SString::c_str().
Referenced by MAssetManager::loadMetaData(), MCubemapAsset::MCubemapAsset(), and MTextureAsset::saveImportSettings().
writeFile()
bool FileIO::writeFile (const SString & path, const SString & data) static
References SString::c_str().
Referenced by MAssetManager::createMetaFile(), MMaterialAsset::createNewMaterial(), MCubemapAsset::save(), MMaterialAsset::save(), MTextAsset::save(), and MTextureAsset::saveImportSettings().
The documentation for this class was generated from the following files:
src/core/utils/fileio.h
src/core/utils/fileio.cpp