Meteor Engine: MMiniAudioEngineSubsystem Class Reference
MMiniAudioEngineSubsystem Class Reference
#include <audio_engine.h>
Public Member Functions
void init () override
void cleanup () override
bool isInitialized () const
IAudioSource * createAudioSource () override
bool releaseAudioSource (IAudioSource *source) override
IAudioListener * createAudioListener () override
bool releaseAudioListener (IAudioListener *listener) override
IAudioClip * createAudioClip (const SString &filePath) override
bool releaseAudioClip (IAudioClip *clip) override
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IAudioEngineSubsystem
~IAudioEngineSubsystem () override=default
Public Member Functions inherited from IEngineSubSystem
virtual ~IEngineSubSystem ()=default
virtual bool canTick ()
virtual void tick (float deltaTime)
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MMiniAudioEngineSubsystem::cleanup () override virtual
Implements IEngineSubSystem.
References MLOG, releaseAudioClip(), releaseAudioListener(), and releaseAudioSource().
createAudioClip()
IAudioClip * MMiniAudioEngineSubsystem::createAudioClip (const SString & filePath) nodiscard override virtual
Implements IAudioEngineSubsystem.
createAudioListener()
IAudioListener * MMiniAudioEngineSubsystem::createAudioListener () nodiscard override virtual
Implements IAudioEngineSubsystem.
createAudioSource()
IAudioSource * MMiniAudioEngineSubsystem::createAudioSource () nodiscard override virtual
Implements IAudioEngineSubsystem.
init()
void MMiniAudioEngineSubsystem::init () override virtual
Implements IEngineSubSystem.
References MERROR, and MLOG.
isInitialized()
bool MMiniAudioEngineSubsystem::isInitialized () const inline nodiscard
releaseAudioClip()
bool MMiniAudioEngineSubsystem::releaseAudioClip (IAudioClip * clip) nodiscard override virtual
Implements IAudioEngineSubsystem.
References IAudioClip::cleanup().
Referenced by cleanup().
releaseAudioListener()
bool MMiniAudioEngineSubsystem::releaseAudioListener (IAudioListener * listener) nodiscard override virtual
Implements IAudioEngineSubsystem.
References IAudioListener::cleanup().
Referenced by cleanup().
releaseAudioSource()
bool MMiniAudioEngineSubsystem::releaseAudioSource (IAudioSource * source) nodiscard override virtual
Implements IAudioEngineSubsystem.
References IAudioSource::cleanup().
Referenced by cleanup().
The documentation for this class was generated from the following files:
src/core/engine/audio/impl_miniaudio/audio_engine.h
src/core/engine/audio/impl_miniaudio/audio_engine.cpp