// CodeEmitter.cs
// Pass 3: Generate .binding.h files for classes and enums using Sol2.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MeteorBindingGenerator;

public static class CodeEmitter
{
    private static HashSet<string> _boundClassNames = new();

    // ---- Class binding emission ---------------------------------------------

    public static string EmitClassBinding(BoundClass cls, string sourceIncludePath)
    {
        var sb = new StringBuilder();
        var guard = $"METEOR_BINDING_{cls.Name.ToUpper()}_H";

        sb.AppendLine($"// {cls.Name}.binding.h");
        sb.AppendLine($"// AUTO-GENERATED by MeteorBindingGenerator. DO NOT EDIT.");
        sb.AppendLine($"// Source: {Path.GetFileName(cls.SourceFile)}");
        sb.AppendLine();
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine($"#include <sol/sol.hpp>");
        sb.AppendLine($"#include \"{sourceIncludePath}\"");
        sb.AppendLine();
        sb.AppendLine($"namespace MeteorBindings {{");
        sb.AppendLine();
        sb.AppendLine($"static void {cls.Name}_registerBinding(sol::state& lua) {{");

        var boundParents = cls.ParentClasses
            .Where(p => _boundClassNames.Contains(p))
            .ToList();

        bool hasMembers = cls.Properties.Count > 0 || cls.Functions.Count > 0;

        if (boundParents.Count == 0 && !hasMembers)
        {
            sb.AppendLine($"    lua.new_usertype<{cls.Name}>(\"{cls.Name}\");");
        }
        else
        {
            sb.AppendLine($"    lua.new_usertype<{cls.Name}>(\"{cls.Name}\",");

            var entries = new List<string>();

            if (boundParents.Count > 0)
            {
                var parentList = string.Join(", ", boundParents);
                entries.Add($"        sol::base_classes, sol::bases<{parentList}>()");

                // Type-casting constructor: ClassName(basePtr) does dynamic_cast.
                // Enables Python-like syntax in Lua:
                //   local derived = MDerived(self:find("./child"))
                // Accepts the first bound parent. dynamic_cast handles the full
                // inheritance chain regardless of how deep the hierarchy is.
                var castFrom = boundParents[0];
                entries.Add(
                    $"        sol::call_constructor, sol::factories(\n" +
                    $"            []({castFrom}* base) -> {cls.Name}* {{\n" +
                    $"                if (!base) return nullptr;\n" +
                    $"                return dynamic_cast<{cls.Name}*>(base);\n" +
                    $"            }}\n" +
                    $"        )");
            }

            foreach (var prop in cls.Properties)
                entries.Add(EmitProperty(cls, prop));

            foreach (var func in cls.Functions)
                entries.Add(EmitFunction(cls, func));

            for (int i = 0; i < entries.Count; i++)
            {
                var comma = (i < entries.Count - 1) ? "," : "";
                sb.AppendLine($"{entries[i]}{comma}");
            }

            sb.AppendLine($"    );");
        }

        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine($"}} // namespace MeteorBindings");
        sb.AppendLine();
        sb.AppendLine($"#endif // {guard}");

        return sb.ToString();
    }

    // ---- Enum binding emission ----------------------------------------------

    public static string EmitEnumBinding(BoundEnum boundEnum, string sourceIncludePath)
    {
        var sb = new StringBuilder();
        var guard = $"METEOR_BINDING_ENUM_{boundEnum.Name.ToUpper()}_H";

        sb.AppendLine($"// {boundEnum.Name}.binding.h");
        sb.AppendLine($"// AUTO-GENERATED by MeteorBindingGenerator. DO NOT EDIT.");
        sb.AppendLine($"// Source: {Path.GetFileName(boundEnum.SourceFile)}");
        sb.AppendLine();
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine($"#include <sol/sol.hpp>");
        sb.AppendLine($"#include \"{sourceIncludePath}\"");
        sb.AppendLine();
        sb.AppendLine($"namespace MeteorBindings {{");
        sb.AppendLine();
        sb.AppendLine($"static void {boundEnum.Name}_registerBinding(sol::state& lua) {{");

        var qualifier = boundEnum.Name + "::";

        sb.AppendLine($"    lua.new_enum<{boundEnum.Name}>(\"{boundEnum.Name}\",");
        sb.AppendLine($"        {{");

        for (int i = 0; i < boundEnum.Values.Count; i++)
        {
            var val = boundEnum.Values[i];
            var comma = (i < boundEnum.Values.Count - 1) ? "," : "";
            sb.AppendLine($"            {{\"{val}\", {qualifier}{val}}}{comma}");
        }

        sb.AppendLine($"        }}");
        sb.AppendLine($"    );");

        sb.AppendLine($"}}");
        sb.AppendLine();
        sb.AppendLine($"}} // namespace MeteorBindings");
        sb.AppendLine();
        sb.AppendLine($"#endif // {guard}");

        return sb.ToString();
    }

    // ---- Batch emission -----------------------------------------------------

    public static List<string> EmitAll(List<BoundClass> boundClasses, List<BoundEnum> boundEnums,
                                        string outputDir, string sourceDir)
    {
        Directory.CreateDirectory(outputDir);
        var generatedFiles = new List<string>();

        _boundClassNames = new HashSet<string>(boundClasses.Select(c => c.Name));

        var normalizedSourceDir = Path.GetFullPath(sourceDir)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        foreach (var boundEnum in boundEnums)
        {
            var fullPath = Path.GetFullPath(boundEnum.SourceFile);
            var relativePath = Path.GetRelativePath(normalizedSourceDir, fullPath)
                                   .Replace('\\', '/');

            var content = EmitEnumBinding(boundEnum, relativePath);
            var fileName = $"{boundEnum.Name}.binding.h";
            var filePath = Path.Combine(outputDir, fileName);
            File.WriteAllText(filePath, content);
            generatedFiles.Add(filePath);
            Console.WriteLine($"  Generated: {fileName} (enum, {boundEnum.Values.Count} values)");
        }

        foreach (var cls in boundClasses)
        {
            var fullPath = Path.GetFullPath(cls.SourceFile);
            var relativePath = Path.GetRelativePath(normalizedSourceDir, fullPath)
                                   .Replace('\\', '/');

            var content = EmitClassBinding(cls, relativePath);
            var fileName = $"{cls.Name}.binding.h";
            var filePath = Path.Combine(outputDir, fileName);
            File.WriteAllText(filePath, content);
            generatedFiles.Add(filePath);

            var boundParents = cls.ParentClasses.Where(p => _boundClassNames.Contains(p)).ToList();
            var parentInfo = boundParents.Count > 0
                ? $" -> [{string.Join(", ", boundParents)}]"
                : "";
            Console.WriteLine($"  Generated: {fileName}{parentInfo}");
        }

        return generatedFiles;
    }

    // ---- Property emission --------------------------------------------------

    private static string EmitProperty(BoundClass cls, BoundProperty prop)
    {
        return prop.AccessKind switch
        {
            PropertyAccessKind.Direct =>
                $"        \"{prop.Name}\", &{cls.Name}::{prop.Name}",

            PropertyAccessKind.DeclareField =>
                $"        \"{prop.Name}\", sol::property(\n" +
                $"            [](const {cls.Name}& self) -> {prop.CppType} {{ return self.{prop.Name}.get(); }},\n" +
                $"            []({cls.Name}& self, const {prop.CppType}& v) {{ self.{prop.Name}.set(v); }}\n" +
                $"        )",

            PropertyAccessKind.RefProp =>
                $"        \"{prop.Name}\", sol::property(\n" +
                $"            [](const {cls.Name}& self) -> {prop.CppType}* {{ return self.{prop.Name}.get(); }}\n" +
                $"        )",

            _ => $"        // TODO: unknown access kind for '{prop.Name}'"
        };
    }

    // ---- Function emission --------------------------------------------------

    private static string EmitFunction(BoundClass cls, BoundFunction func)
    {
        return $"        \"{func.Name}\", &{cls.Name}::{func.Name}";
    }
}