// LuaTypeDefEmitter.cs
// Generates a LuaLS (sumneko) type definition file for IDE autocompletion.
//
// Output: meteor_api.lua
// Contains ---@class, ---@field, ---@param, ---@return, ---@enum annotations
// that LuaLS reads to provide autocomplete, hover docs, and type checking
// in editors like VSCode and JetBrains IDEs.
//
// Place the generated file in your scripts directory (or add its location
// to your .luarc.json workspace.library) and the LSP picks it up.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MeteorBindingGenerator;

public static class LuaTypeDefEmitter
{
    // C++ type -> LuaLS type string
    private static readonly Dictionary<string, string> TypeMap = new()
    {
        ["void"]           = "nil",
        ["int"]            = "integer",
        ["short"]          = "integer",
        ["long"]           = "integer",
        ["long long"]      = "integer",
        ["unsigned int"]   = "integer",
        ["unsigned char"]  = "integer",
        ["unsigned short"] = "integer",
        ["char"]           = "integer",
        ["float"]          = "number",
        ["double"]         = "number",
        ["bool"]           = "boolean",
        ["std::string"]    = "string",
        ["SString"]        = "string",
    };

    /// <summary>
    /// Generate the complete meteor_api.lua type definition file.
    /// </summary>
    public static void Emit(List<BoundClass> boundClasses, List<BoundEnum> boundEnums, string outputDir)
    {
        var sb = new StringBuilder();

        EmitHeader(sb);
        EmitMathTypes(sb);
        EmitEnums(sb, boundEnums);
        EmitClasses(sb, boundClasses);
        EmitSelfGlobal(sb);

        var filePath = Path.Combine(outputDir, "meteor_api.lua");
        File.WriteAllText(filePath, sb.ToString());
        Console.WriteLine($"  Generated: meteor_api.lua (LuaLS type definitions)");
    }

    // ---- Header -------------------------------------------------------------

    private static void EmitHeader(StringBuilder sb)
    {
        sb.AppendLine("---@meta");
        sb.AppendLine("-- meteor_api.lua");
        sb.AppendLine("-- AUTO-GENERATED by MeteorBindingGenerator. DO NOT EDIT.");
        sb.AppendLine("--");
        sb.AppendLine("-- LuaLS (sumneko) type definitions for the Meteor engine Lua API.");
        sb.AppendLine("-- Place this file in your scripts directory or add its path to");
        sb.AppendLine("-- .luarc.json \"workspace.library\" for IDE autocompletion.");
        sb.AppendLine();
    }

    // ---- Math types (manually bound, not generated) -------------------------

    private static void EmitMathTypes(StringBuilder sb)
    {
        sb.AppendLine("-- ============================================================");
        sb.AppendLine("-- Math Types (manually bound via math_bindings.h)");
        sb.AppendLine("-- ============================================================");
        sb.AppendLine();

        // SVector2
        sb.AppendLine("---@class SVector2");
        sb.AppendLine("---@field x number");
        sb.AppendLine("---@field y number");
        sb.AppendLine("---@operator add(SVector2): SVector2");
        sb.AppendLine("---@operator sub(SVector2): SVector2");
        sb.AppendLine("---@operator mul(number): SVector2");
        sb.AppendLine("SVector2 = {}");
        sb.AppendLine();
        sb.AppendLine("---@param x number");
        sb.AppendLine("---@param y number");
        sb.AppendLine("---@return SVector2");
        sb.AppendLine("function SVector2.new(x, y) end");
        sb.AppendLine();

        // SVector3
        sb.AppendLine("---@class SVector3");
        sb.AppendLine("---@field x number");
        sb.AppendLine("---@field y number");
        sb.AppendLine("---@field z number");
        sb.AppendLine("---@operator add(SVector3): SVector3");
        sb.AppendLine("---@operator sub(SVector3): SVector3");
        sb.AppendLine("---@operator mul(number): SVector3");
        sb.AppendLine("---@operator unm: SVector3");
        sb.AppendLine("SVector3 = {}");
        sb.AppendLine();
        sb.AppendLine("---@param x number");
        sb.AppendLine("---@param y number");
        sb.AppendLine("---@param z number");
        sb.AppendLine("---@return SVector3");
        sb.AppendLine("function SVector3.new(x, y, z) end");
        sb.AppendLine();
        sb.AppendLine("---@return number");
        sb.AppendLine("function SVector3:length() end");
        sb.AppendLine();
        sb.AppendLine("---@return SVector3");
        sb.AppendLine("function SVector3:normalized() end");
        sb.AppendLine();
        sb.AppendLine("---@param a SVector3");
        sb.AppendLine("---@param b SVector3");
        sb.AppendLine("---@return number");
        sb.AppendLine("function SVector3.dot(a, b) end");
        sb.AppendLine();
        sb.AppendLine("---@param a SVector3");
        sb.AppendLine("---@param b SVector3");
        sb.AppendLine("---@return SVector3");
        sb.AppendLine("function SVector3.cross(a, b) end");
        sb.AppendLine();
        sb.AppendLine("---@param a SVector3");
        sb.AppendLine("---@param b SVector3");
        sb.AppendLine("---@param t number");
        sb.AppendLine("---@return SVector3");
        sb.AppendLine("function SVector3.lerp(a, b, t) end");
        sb.AppendLine();

        // SVector4
        sb.AppendLine("---@class SVector4");
        sb.AppendLine("---@field x number");
        sb.AppendLine("---@field y number");
        sb.AppendLine("---@field z number");
        sb.AppendLine("---@field w number");
        sb.AppendLine("---@operator add(SVector4): SVector4");
        sb.AppendLine("---@operator sub(SVector4): SVector4");
        sb.AppendLine("---@operator mul(number): SVector4");
        sb.AppendLine("SVector4 = {}");
        sb.AppendLine();
        sb.AppendLine("---@param x number");
        sb.AppendLine("---@param y number");
        sb.AppendLine("---@param z number");
        sb.AppendLine("---@param w number");
        sb.AppendLine("---@return SVector4");
        sb.AppendLine("function SVector4.new(x, y, z, w) end");
        sb.AppendLine();

        // SQuaternion
        sb.AppendLine("---@class SQuaternion");
        sb.AppendLine("---@field x number");
        sb.AppendLine("---@field y number");
        sb.AppendLine("---@field z number");
        sb.AppendLine("---@field w number");
        sb.AppendLine("---@operator mul(SQuaternion): SQuaternion");
        sb.AppendLine("SQuaternion = {}");
        sb.AppendLine();
        sb.AppendLine("---@param x number");
        sb.AppendLine("---@param y number");
        sb.AppendLine("---@param z number");
        sb.AppendLine("---@param w number");
        sb.AppendLine("---@return SQuaternion");
        sb.AppendLine("function SQuaternion.new(x, y, z, w) end");
        sb.AppendLine();
        sb.AppendLine("---@return SVector3");
        sb.AppendLine("function SQuaternion:toEuler() end");
        sb.AppendLine();
        sb.AppendLine("---@return SQuaternion");
        sb.AppendLine("function SQuaternion:normalized() end");
        sb.AppendLine();
        sb.AppendLine("---@return SQuaternion");
        sb.AppendLine("function SQuaternion:inverse() end");
        sb.AppendLine();
        sb.AppendLine("---@param a SQuaternion");
        sb.AppendLine("---@param b SQuaternion");
        sb.AppendLine("---@param t number");
        sb.AppendLine("---@return SQuaternion");
        sb.AppendLine("function SQuaternion.slerp(a, b, t) end");
        sb.AppendLine();

        // SColor (if bound manually)
        sb.AppendLine("---@class SColor");
        sb.AppendLine("---@field r number");
        sb.AppendLine("---@field g number");
        sb.AppendLine("---@field b number");
        sb.AppendLine("---@field a number");
        sb.AppendLine("SColor = {}");
        sb.AppendLine();

        // Free functions
        sb.AppendLine("---@param x number");
        sb.AppendLine("---@param y number");
        sb.AppendLine("---@param z number");
        sb.AppendLine("---@return SQuaternion");
        sb.AppendLine("function eulerToQuaternion(x, y, z) end");
        sb.AppendLine();

        // MLogger (static utility, manually bound)
        sb.AppendLine("---@class MLogger");
        sb.AppendLine("MLogger = {}");
        sb.AppendLine();
        sb.AppendLine("---@param msg string");
        sb.AppendLine("function MLogger.info(msg) end");
        sb.AppendLine();
        sb.AppendLine("---@param msg string");
        sb.AppendLine("function MLogger.verbose(msg) end");
        sb.AppendLine();
        sb.AppendLine("---@param msg string");
        sb.AppendLine("function MLogger.warn(msg) end");
        sb.AppendLine();
        sb.AppendLine("---@param msg string");
        sb.AppendLine("function MLogger.error(msg) end");
        sb.AppendLine();

        // Behaviour (Lua-side base class for script types)
        sb.AppendLine("-- ---- Script System ----");
        sb.AppendLine();
        sb.AppendLine("---@class Behaviour");
        sb.AppendLine("Behaviour = {}");
        sb.AppendLine();
        sb.AppendLine("function Behaviour:onStart() end");
        sb.AppendLine("function Behaviour:onTick(dt) end");
        sb.AppendLine("function Behaviour:onFixedTick(dt) end");
        sb.AppendLine("function Behaviour:onStop() end");
        sb.AppendLine();
        sb.AppendLine("--- Create a new class extending this one.");
        sb.AppendLine("---@return table");
        sb.AppendLine("function Behaviour:extend() end");
        sb.AppendLine();

        // Script access methods (manually bound on MSpatialEntity)
        sb.AppendLine("--- Get the script table from this entity for cross-script access.");
        sb.AppendLine("---@return table|nil");
        sb.AppendLine("function MSpatialEntity:getScript() end");
        sb.AppendLine();
    }

    // ---- Enums --------------------------------------------------------------

    private static void EmitEnums(StringBuilder sb, List<BoundEnum> enums)
    {
        if (enums.Count == 0) return;

        sb.AppendLine("-- ============================================================");
        sb.AppendLine("-- Enums");
        sb.AppendLine("-- ============================================================");
        sb.AppendLine();

        foreach (var e in enums)
        {
            sb.AppendLine($"---@enum {e.Name}");
            sb.AppendLine($"{e.Name} = {{");
            for (int i = 0; i < e.Values.Count; i++)
            {
                var comma = (i < e.Values.Count - 1) ? "," : "";
                sb.AppendLine($"    {e.Values[i]} = {i}{comma}");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }
    }

    // ---- Classes ------------------------------------------------------------

    private static void EmitClasses(StringBuilder sb, List<BoundClass> classes)
    {
        if (classes.Count == 0) return;

        // Build set of bound class names for parent resolution
        var boundNames = new HashSet<string>(classes.Select(c => c.Name));

        sb.AppendLine("-- ============================================================");
        sb.AppendLine("-- Classes");
        sb.AppendLine("-- ============================================================");
        sb.AppendLine();

        foreach (var cls in classes)
        {
            // Class declaration with optional parent
            var boundParent = cls.ParentClasses.FirstOrDefault(p => boundNames.Contains(p));
            if (boundParent != null)
                sb.AppendLine($"---@class {cls.Name} : {boundParent}");
            else
                sb.AppendLine($"---@class {cls.Name}");

            // Properties as fields
            foreach (var prop in cls.Properties)
            {
                var luaType = MapType(prop.CppType);
                sb.AppendLine($"---@field {prop.Name} {luaType}");
            }

            sb.AppendLine($"{cls.Name} = {{}}");
            sb.AppendLine();

            // Methods
            foreach (var func in cls.Functions)
            {
                EmitFunction(sb, cls.Name, func);
            }
        }
    }

    // ---- Function emission --------------------------------------------------

    private static void EmitFunction(StringBuilder sb, string className, BoundFunction func)
    {
        // Parameter annotations
        foreach (var (type, name) in func.Parameters)
        {
            var luaType = MapType(type);
            sb.AppendLine($"---@param {name} {luaType}");
        }

        // Return annotation (skip for void)
        if (func.ReturnType != "void")
        {
            var luaReturn = MapType(func.ReturnType);
            sb.AppendLine($"---@return {luaReturn}");
        }

        // Function signature: static uses dot, instance uses colon
        var paramNames = string.Join(", ", func.Parameters.Select(p => p.Name));
        var separator = func.IsStatic ? "." : ":";
        sb.AppendLine($"function {className}{separator}{func.Name}({paramNames}) end");
        sb.AppendLine();
    }

    // ---- Self global --------------------------------------------------------

    private static void EmitSelfGlobal(StringBuilder sb)
    {
        sb.AppendLine("-- ============================================================");
        sb.AppendLine("-- Global 'self' reference");
        sb.AppendLine("-- ============================================================");
        sb.AppendLine("-- The engine injects 'self' into every script environment,");
        sb.AppendLine("-- pointing to the owning MSpatialEntity (or subclass).");
        sb.AppendLine("-- Type it as MSpatialEntity for base autocompletion.");
        sb.AppendLine("-- Scripts for specific entity types can override with:");
        sb.AppendLine("--   ---@type MCollisionBodyEntity");
        sb.AppendLine("--   local self = self");
        sb.AppendLine();
        sb.AppendLine("---@type MSpatialEntity");
        sb.AppendLine("self = nil");
    }

    // ---- Type mapping -------------------------------------------------------

    /// <summary>
    /// Map a C++ type string to a LuaLS type annotation.
    /// Known primitives map to number/boolean/string.
    /// Everything else passes through as a class name (stripping const/ref/ptr).
    /// </summary>
    private static string MapType(string cppType)
    {
        // Strip const, &, * qualifiers for lookup
        var cleaned = cppType
            .Replace("const ", "")
            .Replace("&", "")
            .Replace("*", "")
            .Trim();

        if (TypeMap.TryGetValue(cleaned, out var luaType))
            return luaType;

        // If it's a known class/enum name, return as-is
        // Otherwise return as-is too (it might be a class the user hasn't bound yet)
        return cleaned;
    }
}