// RegistryEmitter.cs
// Generates binding_registry.generated.h.
// Registration order: enums first, then classes (topologically sorted).

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace MeteorBindingGenerator;

public static class RegistryEmitter
{
    public static void Emit(List<BoundClass> boundClasses, List<BoundEnum> boundEnums, string outputDir)
    {
        var sortedClasses = TopologicalSort(boundClasses);
        var sb = new StringBuilder();

        sb.AppendLine("// binding_registry.generated.h");
        sb.AppendLine("// AUTO-GENERATED by MeteorBindingGenerator. DO NOT EDIT.");
        sb.AppendLine("//");
        sb.AppendLine("// Call MeteorBindings::registerAllBindings(lua) once after");
        sb.AppendLine("// creating the sol::state to register all script-bound types.");
        sb.AppendLine("//");
        sb.AppendLine("// Registration order: enums, then classes (parents before children).");
        sb.AppendLine();
        sb.AppendLine("#ifndef METEOR_BINDING_REGISTRY_GENERATED_H");
        sb.AppendLine("#define METEOR_BINDING_REGISTRY_GENERATED_H");
        sb.AppendLine();
        sb.AppendLine("#include <sol/sol.hpp>");
        sb.AppendLine();

        // Include enum bindings
        foreach (var e in boundEnums)
            sb.AppendLine($"#include \"{e.Name}.binding.h\"");

        // Include class bindings
        foreach (var cls in sortedClasses)
            sb.AppendLine($"#include \"{cls.Name}.binding.h\"");

        sb.AppendLine();
        sb.AppendLine("namespace MeteorBindings {");
        sb.AppendLine();
        sb.AppendLine("static void registerAllBindings(sol::state& lua) {");

        // Register enums first (classes may use them as param/field types)
        foreach (var e in boundEnums)
            sb.AppendLine($"    {e.Name}_registerBinding(lua);");

        if (boundEnums.Count > 0 && sortedClasses.Count > 0)
            sb.AppendLine();

        // Register classes in dependency order
        foreach (var cls in sortedClasses)
            sb.AppendLine($"    {cls.Name}_registerBinding(lua);");

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("} // namespace MeteorBindings");
        sb.AppendLine();
        sb.AppendLine("#endif // METEOR_BINDING_REGISTRY_GENERATED_H");

        var filePath = Path.Combine(outputDir, "binding_registry.generated.h");
        File.WriteAllText(filePath, sb.ToString());
        Console.WriteLine($"  Generated: binding_registry.generated.h");
    }

    private static List<BoundClass> TopologicalSort(List<BoundClass> classes)
    {
        var nameToClass = new Dictionary<string, BoundClass>();
        foreach (var cls in classes)
            nameToClass[cls.Name] = cls;

        var inDegree = new Dictionary<string, int>();
        var childrenOf = new Dictionary<string, List<string>>();

        foreach (var cls in classes)
        {
            inDegree[cls.Name] = 0;
            childrenOf[cls.Name] = new List<string>();
        }

        foreach (var cls in classes)
        {
            foreach (var parent in cls.ParentClasses)
            {
                if (!nameToClass.ContainsKey(parent)) continue;
                childrenOf[parent].Add(cls.Name);
                inDegree[cls.Name]++;
            }
        }

        var queue = new Queue<string>();
        foreach (var (name, degree) in inDegree)
        {
            if (degree == 0)
                queue.Enqueue(name);
        }

        var sorted = new List<BoundClass>();
        while (queue.Count > 0)
        {
            var current = queue.Dequeue();
            sorted.Add(nameToClass[current]);

            foreach (var child in childrenOf[current])
            {
                inDegree[child]--;
                if (inDegree[child] == 0)
                    queue.Enqueue(child);
            }
        }

        if (sorted.Count < classes.Count)
        {
            var missing = classes.Where(c => !sorted.Contains(c)).Select(c => c.Name);
            Console.Error.WriteLine(
                $"[WARNING] Circular inheritance detected among: {string.Join(", ", missing)}. " +
                $"These classes will be appended in scan order.");
            foreach (var cls in classes)
            {
                if (!sorted.Contains(cls))
                    sorted.Add(cls);
            }
        }

        return sorted;
    }
}