Meteor Engine: MGizmoStage Class Reference
MGizmoStage Class Reference
#include <gizmo_stage.h>
Public Member Functions
int getSortingOrder () override
void init (IRenderPipeline *const pipeline) override
void cleanup (IRenderPipeline *const pipeline) override
void preRender (IRenderPipeline *const pipeline) override
void render (IRenderPipeline *const pipeline) override
void postRender (IRenderPipeline *const pipeline) override
Public Member Functions inherited from MRenderStage
MRenderStage ()=default
~MRenderStage () override=default
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Public Member Functions inherited from IRenderStage
virtual ~IRenderStage ()=default
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
cleanup()
void MGizmoStage::cleanup (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
getSortingOrder()
int MGizmoStage::getSortingOrder () inline override virtual
Implements MRenderStage.
References RS_Composite.
init()
void MGizmoStage::init (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
postRender()
void MGizmoStage::postRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
preRender()
void MGizmoStage::preRender (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
render()
void MGizmoStage::render (IRenderPipeline *const pipeline) override virtual
Implements MRenderStage.
References SRenderBuffer::bindAsActive(), MBufferNames::BUFFER_OPAQUE, MBufferRegistery::getBuffer(), IRenderPipeline::getBufferRegistry(), IRenderPipeline::getRenderBuffer(), IRenderPipeline::getRenderResolution(), and MGizmos::requestGizmoDraws().
The documentation for this class was generated from the following files:
src/editor/editorrenderstages/gizmos/gizmo_stage.h
src/editor/editorrenderstages/gizmos/gizmo_stage.cpp