Meteor Engine: MInspectorDrawer Class Reference
MInspectorDrawer Class Reference abstract
#include <inspectordrawer.h>
Public Member Functions
void onDraw (MSpatialEntity *target)
virtual SString getInspectorName () const =0
virtual bool canDraw (MSpatialEntity *entity)=0
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Static Public Member Functions
static void initialise ()
static void registerDrawer (MInspectorDrawer *drawer)
static MInspectorDrawer * getDrawer (MSpatialEntity *entity)
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Protected Member Functions
virtual void onDrawInspector (MSpatialEntity *target)=0
virtual void drawDefaultFields (MSpatialEntity *)
Additional Inherited Members
Protected Attributes inherited from MObject
SString guid
SString name
Member Function Documentation
canDraw()
virtual bool MInspectorDrawer::canDraw (MSpatialEntity * entity) pure virtual
Implemented in MAmbientLightInspectorDrawer, MAudioSourceInspectorDrawer, MCameraEntityInspectorDrawer, MDirecionalLightInspectorDrawer, MPointLightInspectorDrawer, MProceduralSkyInspectorDrawer, MSkyboxInspectorDrawer, MSpatialEntityInspectorDrawer, MSpotLightInspectorDrawer, and MStaticMeshInspectorDrawer.
drawDefaultFields()
virtual void MInspectorDrawer::drawDefaultFields (MSpatialEntity *) inline protected virtual
Reimplemented in MSpatialEntityInspectorDrawer.
Referenced by onDraw().
getDrawer()
MInspectorDrawer * MInspectorDrawer::getDrawer (MSpatialEntity * entity) static
Referenced by MEditorInspectorWindow::onGui().
getInspectorName()
virtual SString MInspectorDrawer::getInspectorName () const pure virtual
Implemented in MAmbientLightInspectorDrawer, MAudioSourceInspectorDrawer, MCameraEntityInspectorDrawer, MDirecionalLightInspectorDrawer, MPointLightInspectorDrawer, MProceduralSkyInspectorDrawer, MSkyboxInspectorDrawer, MSpatialEntityInspectorDrawer, MSpotLightInspectorDrawer, and MStaticMeshInspectorDrawer.
initialise()
void MInspectorDrawer::initialise () static
Referenced by MEditorInspectorWindow::MEditorInspectorWindow().
onDraw()
void MInspectorDrawer::onDraw (MSpatialEntity * target)
References drawDefaultFields(), and onDrawInspector().
onDrawInspector()
virtual void MInspectorDrawer::onDrawInspector (MSpatialEntity * target) protected pure virtual
Implemented in MAmbientLightInspectorDrawer, MAudioSourceInspectorDrawer, MDirecionalLightInspectorDrawer, MPointLightInspectorDrawer, MProceduralSkyInspectorDrawer, MSkyboxInspectorDrawer, MSpatialEntityInspectorDrawer, MSpotLightInspectorDrawer, and MStaticMeshInspectorDrawer.
Referenced by onDraw().
registerDrawer()
void MInspectorDrawer::registerDrawer (MInspectorDrawer * drawer) static
The documentation for this class was generated from the following files:
src/editor/editorwindows/inspectordrawer/inspectordrawer.h
src/editor/editorwindows/inspectordrawer/inspectordrawer.cpp