Meteor Engine: MAssetInspector Class Reference
MAssetInspector Class Reference
#include <asset_inspector.h>
Static Public Member Functions
static void draw (MAsset *asset)
static void releaseAudioPreview ()
Member Function Documentation
draw()
void MAssetInspector::draw (MAsset * asset) static
References MAsset::getAssetId(), and releaseAudioPreview().
Referenced by MEditorInspectorWindow::onGui().
releaseAudioPreview()
void MAssetInspector::releaseAudioPreview () static
References MEngineSubsystemRegistry::getSubsystem(), and IAudioEngineSubsystem::releaseAudioSource().
Referenced by draw().
The documentation for this class was generated from the following files:
src/editor/editorwindows/inspector/asset_inspector.h
src/editor/editorwindows/inspector/asset_inspector.cpp