Meteor Engine: MAsset Class Reference
MAsset Class Reference abstract
#include <asset.h>
Public Member Functions
MAsset (const SString &path)
~MAsset () override=default
SString getPath () const
SString getFullPath () const
bool isValid () const
SString getAssetId () const
void internal_SetAssetId (const SString &assetId)
virtual bool openAsset ()
virtual bool requestReload ()=0
virtual bool save ()
virtual bool hasDeferredLoad () const override
virtual void deferredAssetLoad (bool forced) override
Public Member Functions inherited from MObject
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Protected Attributes
SString path
SString assetId
bool valid = false
Protected Attributes inherited from MObject
SString guid
SString name
Additional Inherited Members
Static Public Member Functions inherited from MObject
static void operator delete (void *ptr)
Constructor & Destructor Documentation
MAsset()
MAsset::MAsset (const SString & path)
References MObject::name, and path.
Referenced by MAudioClipAsset::MAudioClipAsset(), MMaterialAsset::MMaterialAsset(), MSceneAsset::MSceneAsset(), MShaderAsset::MShaderAsset(), MStaticMeshAsset::MStaticMeshAsset(), MTextAsset::MTextAsset(), MTextureAsset::MTextureAsset(), MTextureAsset::MTextureAsset(), and MTextureAsset::MTextureAsset().
~MAsset()
MAsset::~MAsset () override default
Member Function Documentation
deferredAssetLoad()
virtual void MAsset::deferredAssetLoad (bool forced) inline override virtual
Override this method to do all loading asset after all other independent assets are ready.
This does not guarantee that all deferred loads will succeed, since an asset could be dependent on another deferred load asset, at this point the order will dictate the asset-load success
Implements IDefferedLoadableAsset.
Reimplemented in MCubemapAsset, and MMaterialAsset.
getAssetId()
SString MAsset::getAssetId () const inline
References assetId.
Referenced by MAssetInspector::draw(), MEditorAssetManager::getThumbnail(), and MThumbnailRenderer::requestThumbnail().
getFullPath()
SString MAsset::getFullPath () const
References FileIO::getWorkingDir(), and path.
Referenced by MEditorAssetManager::openAsset().
getPath()
SString MAsset::getPath () const
References path.
Referenced by MAudioClipAsset::getAudioClip(), MAudioClipAsset::save(), and MHotReloadWatcher::watchAsset().
hasDeferredLoad()
virtual bool MAsset::hasDeferredLoad () const inline override virtual
Inform that this asset needs deferred loading.
By default, the assets do not need deferred loading, but some assets like material will need to depend on another asset like shader to get all available properties for a specific shader. so setting this true, will allow the asset to have another pass at loading after all independent assets are loaded, giving the dependencies to be resolved without any issue
Implements IDefferedLoadableAsset.
Reimplemented in MAudioClipAsset, MCubemapAsset, and MMaterialAsset.
internal_SetAssetId()
void MAsset::internal_SetAssetId (const SString & assetId)
References assetId.
isValid()
bool MAsset::isValid () const
References valid.
Referenced by MCubemapAssetImporter::importAsset(), and MTextureAssetImporter::importAsset().
openAsset()
virtual bool MAsset::openAsset () inline virtual
Reimplemented in MSceneAsset.
Referenced by MEditorAssetManager::openAsset().
requestReload()
virtual bool MAsset::requestReload () pure virtual
Implemented in MAudioClipAsset, MCubemapAsset, MMaterialAsset, MSceneAsset, MShaderAsset, MStaticMeshAsset, MTextAsset, and MTextureAsset.
save()
virtual bool MAsset::save () inline virtual
Reimplemented in MAudioClipAsset, MCubemapAsset, MMaterialAsset, and MTextAsset.
Referenced by MEditorAssetManager::saveDirtyAssets().
Member Data Documentation
assetId
SString MAsset::assetId protected
Referenced by getAssetId(), and internal_SetAssetId().
path
SString MAsset::path protected
Referenced by MCubemapAsset::deferredAssetLoad(), getFullPath(), getPath(), MAsset(), MAudioClipAsset::MAudioClipAsset(), MCubemapAsset::MCubemapAsset(), MMaterialAsset::MMaterialAsset(), MSceneAsset::MSceneAsset(), MShaderAsset::MShaderAsset(), MStaticMeshAsset::MStaticMeshAsset(), MTextAsset::MTextAsset(), MTextureAsset::MTextureAsset(), MTextureAsset::MTextureAsset(), MSceneAsset::openAsset(), MMaterialAsset::requestReload(), MSceneAsset::requestReload(), MShaderAsset::requestReload(), MStaticMeshAsset::requestReload(), MTextAsset::requestReload(), MCubemapAsset::save(), MMaterialAsset::save(), MTextAsset::save(), and MTextureAsset::saveImportSettings().
valid
bool MAsset::valid = false protected
Referenced by MMaterialAsset::getMaterial(), isValid(), MCubemapAsset::MCubemapAsset(), MMaterialAsset::MMaterialAsset(), MSceneAsset::MSceneAsset(), MTextAsset::MTextAsset(), MTextureAsset::MTextureAsset(), MTextureAsset::MTextureAsset(), MCubemapAsset::requestReload(), MMaterialAsset::requestReload(), MShaderAsset::requestReload(), MStaticMeshAsset::requestReload(), MTextureAsset::requestReload(), and MShaderAsset::~MShaderAsset().
The documentation for this class was generated from the following files:
src/core/engine/assetmanagement/asset/asset.h
src/core/engine/assetmanagement/asset/asset.cpp