Meteor Engine: src/main.cpp File Reference
main.cpp File Reference
#include <GL/glew.h>
#include "SFML/OpenGL.hpp"
#include "core/engine/audio/impl_miniaudio/audio_engine.h"
#include "core/engine/audio/impl_miniaudio/audio_listener.h"
#include "core/engine/audio/impl_miniaudio/audio_source.h"
#include "core/engine/audio/interfaces/engine_interface.h"
#include "core/engine/engine_statics.h"
#include "core/engine/subsystem/subsystem_registry.h"
#include "core/meteor_core.h"
#include "data/serialized_class_base.h"
#include "imgui-SFML.h"
#include "imgui.h"
Functions
MApplication * getAppInstance ()
int main ()
Function Documentation
getAppInstance()
MApplication * getAppInstance () extern
Referenced by main().
main()
int main ()
Entry point for the application. depending on build mode, Application will load the appropriate instance and run it.
References MEngineSubsystemRegistry::cleanup(), getAppInstance(), MEngineSubsystemRegistry::init(), MERROR, MEngineStatics::saveAll(), and STR.