Meteor Engine: MObject Class Reference
MObject Class Reference
#include <object.h>
Public Member Functions
MObject ()
virtual ~MObject ()=default
SString getGUID () const
virtual SString toString () const
virtual bool equals (const MObject *obj) const
void setName (const SString &newName)
SString getName () const
void markDirty ()
void clearDirty ()
bool isDirty () const
Static Public Member Functions
static void operator delete (void *ptr)
Protected Attributes
SString guid
SString name
Constructor & Destructor Documentation
MObject()
MObject::MObject ()
References SString::format(), guid, MVERBOSE, name, and SGuid::newGUID().
Referenced by equals(), MMaterial::MMaterial(), operator delete(), and ~MObject().
~MObject()
virtual MObject::~MObject () virtual default
References MObject().
Member Function Documentation
clearDirty()
void MObject::clearDirty () inline
Referenced by MEditorAssetManager::saveDirtyAssets().
equals()
bool MObject::equals (const MObject * obj) const nodiscard virtual
References guid, and MObject().
getGUID()
SString MObject::getGUID () const nodiscard
References guid.
Referenced by MAssetReferenceControl::drawCompactControl().
getName()
SString MObject::getName () const inline nodiscard
References name.
Referenced by MGarbageCollector::dereference(), MSpatialEntity::destroy(), MSpatialEntityInspectorDrawer::onDrawInspector(), MSpatialEntity::onSerialise(), MEditorAssetManager::openAsset(), MSceneSerializer::save(), and MSceneEntityTypeDeserializer::writeSpatialBase().
isDirty()
bool MObject::isDirty () const inline nodiscard
Referenced by MEditorAssetManager::getThumbnail(), and MEditorAssetManager::saveDirtyAssets().
markDirty()
void MObject::markDirty () inline
operator delete()
void MObject::operator delete (void * ptr) static
References SString::format(), MObject(), and MVERBOSE.
setName()
void MObject::setName (const SString & newName) inline
References name.
Referenced by MSpatialEntity::createInstance(), MSceneSerializer::load(), MSpatialEntity::onDeserialise(), MSpatialEntityInspectorDrawer::onDrawInspector(), and MSceneEntityTypeDeserializer::parseSpatialData().
toString()
SString MObject::toString () const nodiscard virtual
References guid, name, and STR.
Member Data Documentation
guid
SString MObject::guid protected
Referenced by equals(), getGUID(), MObject(), and toString().
name
SString MObject::name protected
Referenced by MScene::close(), MShaderCompiler::compileShader(), MBufferRegistery::createBuffer(), MSpatialEntity::createInstance(), MSpatialEntity::createInstance(), MScene::find(), MSpatialEntity::find(), MBufferRegistery::getBuffer(), FileIO::getFileNameWithoutExtension(), getName(), MEntityTypeRegistry::hasType(), MWindow::initialiseWindow(), MAsset::MAsset(), MAudioClipAsset::MAudioClipAsset(), MCameraEntity::MCameraEntity(), MCubemapAsset::MCubemapAsset(), MEditorApplication::MEditorApplication(), MMaterial::MMaterial(), MObject(), MPlayerApplication::MPlayerApplication(), MProceduralSkyboxEntity::MProceduralSkyboxEntity(), MScene::MScene(), MSceneAsset::MSceneAsset(), MShaderAsset::MShaderAsset(), MSkyboxEntity::MSkyboxEntity(), MSpatialEntity::MSpatialEntity(), MStaticMeshEntity::MStaticMeshEntity(), MTextAsset::MTextAsset(), MSpatialEntityInspectorDrawer::onDrawInspector(), MBufferRegistery::resizeAll(), MCubemapAsset::save(), MMaterialAsset::save(), setName(), MMaterial::setProperty(), MShader::setPropertyValue(), toString(), MScene::tryParse(), MBufferRegistery::~MBufferRegistery(), and MMaterial::~MMaterial().
The documentation for this class was generated from the following files:
src/core/object/object.h
src/core/object/object.cpp