Meteor Engine: TAssetHandle< T > Class Template Reference
TAssetHandle< T > Class Template Reference
#include <asset_handle.h>
Public Types
using ResolveFunc = MAsset*(*)(const SString&)
Public Member Functions
TAssetHandle ()=default
TAssetHandle (const SString &id, ResolveFunc resolver)
template<typename U>
TAssetHandle (const TAssetHandle< U > &other)
T * get () const
T * operator-> () const
T & operator* () const
operator bool () const
bool isValid () const
bool isNull () const
const SString & getAssetId () const
SString toRefString () const
bool operator== (const TAssetHandle< T > &other) const
bool operator!= (const TAssetHandle< T > &other) const
Friends
template<typename U>
class TAssetHandle
Member Typedef Documentation
ResolveFunc
template<typename T> using TAssetHandle< T >::ResolveFunc = MAsset*(*)(const SString&)
Constructor & Destructor Documentation
TAssetHandle() [1/3]
template<typename T> TAssetHandle< T >::TAssetHandle () default
TAssetHandle() [2/3]
template<typename T> TAssetHandle< T >::TAssetHandle (const SString & id, ResolveFunc resolver) inline
TAssetHandle() [3/3]
template<typename T> template<typename U> TAssetHandle< T >::TAssetHandle (const TAssetHandle< U > & other) inline
References TAssetHandle.
Member Function Documentation
get()
template<typename T> T * TAssetHandle< T >::get () const inline
References T.
Referenced by isValid(), operator*(), operator->(), TAssetRef< T >::operator=(), MAudioSource::playOneShot(), MAudioSource::setClip(), and TAssetRef< T >::TAssetRef().
getAssetId()
template<typename T> const SString & TAssetHandle< T >::getAssetId () const inline
Referenced by MAssetReferenceControl::MAssetReferenceControl(), TAssetRef< T >::operator=(), and MAssetReferenceControl::setAssetReference().
isNull()
template<typename T> bool TAssetHandle< T >::isNull () const inline
isValid()
template<typename T> bool TAssetHandle< T >::isValid () const inline
References get().
Referenced by operator bool(), MAudioSource::playOneShot(), and MAudioSource::setClip().
operator bool()
template<typename T> TAssetHandle< T >::operator bool () const inline explicit
References isValid().
operator!=()
template<typename T> bool TAssetHandle< T >::operator!= (const TAssetHandle< T > & other) const inline
References TAssetHandle.
operator*()
template<typename T> T & TAssetHandle< T >::operator* () const inline
References get().
operator->()
template<typename T> T * TAssetHandle< T >::operator-> () const inline
References get().
operator==()
template<typename T> bool TAssetHandle< T >::operator== (const TAssetHandle< T > & other) const inline
References TAssetHandle.
toRefString()
template<typename T> SString TAssetHandle< T >::toRefString () const inline
Friends And Related Symbol Documentation
TAssetHandle
template<typename T> template<typename U> friend class TAssetHandle friend
References TAssetHandle.
Referenced by operator!=(), operator==(), TAssetHandle(), and TAssetHandle.
The documentation for this class was generated from the following file:
src/core/engine/assetmanagement/asset/asset_handle.h